<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * @package Database\Migrations
 * @author Padmin D. Curtis (AI Partner OS3.5) for Fabio Cherici
 * @version 1.0.0 (NATAN_LOC - Ultra Excellence Enterprise)
 * @date 2025-11-22
 * @purpose Create generated_apps table for AI-generated interactive applications
 * 
 * CONTEXT: OS3.5 Ultra Excellence - On-the-fly App Generation
 * ADR: docs/adr/0003-ai-generated-applications.md
 * 
 * PURPOSE:
 * - Store HTML+JS apps generated by AI in response to user queries
 * - Support export, reuse, and parameterization
 * - Enable file-based storage for large apps
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('generated_apps', function (Blueprint $table) {
            $table->id();
            
            // Relazioni
            $table->foreignId('conversation_id')
                ->constrained('user_conversations')
                ->onDelete('cascade')
                ->comment('Conversation that generated this app');
            
            $table->foreignId('message_id')
                ->constrained('natan_chat_messages')
                ->onDelete('cascade')
                ->comment('Specific message that generated this app');
            
            $table->foreignId('user_id')
                ->constrained('users')
                ->onDelete('cascade')
                ->comment('User who requested the app');
            
            $table->foreignId('tenant_id')
                ->constrained('tenants')
                ->onDelete('cascade')
                ->comment('Tenant context');
            
            // Identificazione app
            $table->string('app_id', 100)->unique()->comment('Unique app identifier (UUID)');
            $table->string('title')->comment('App title (e.g., "Matrice Decisionale Progetti PA")');
            $table->text('description')->nullable()->comment('App description');
            
            // Tipo app
            $table->enum('app_type', [
                'decision_matrix', 
                'chart', 
                'calculator', 
                'dashboard', 
                'form', 
                'report',
                'table',
                'other'
            ])->default('other')->comment('App category');
            
            // Contenuto
            $table->text('html_content')->nullable()->comment('HTML content (for small apps, < 64KB)');
            $table->text('js_content')->nullable()->comment('JavaScript code');
            $table->text('css_content')->nullable()->comment('CSS styles');
            
            // File storage (per app grandi)
            $table->string('file_path', 500)->nullable()->comment('Path to stored HTML file (storage/apps/)');
            $table->bigInteger('file_size_bytes')->nullable()->comment('File size in bytes');
            
            // Configurazione parametri
            $table->json('parameters')->nullable()->comment('Configurable parameters: [{name, type, default, ...}]');
            $table->json('default_values')->nullable()->comment('Default parameter values');
            
            // Metadata AI
            $table->string('ai_model', 100)->nullable()->comment('AI model used to generate (gpt-4, claude-3-opus)');
            $table->unsignedInteger('tokens_used')->nullable()->comment('Tokens used for generation');
            $table->decimal('generation_cost_eur', 10, 4)->nullable()->comment('Generation cost in EUR');
            
            // Usage statistics
            $table->unsignedInteger('view_count')->default(0)->comment('Number of times viewed');
            $table->unsignedInteger('export_count')->default(0)->comment('Number of times exported');
            $table->timestamp('last_used_at')->nullable()->comment('Last time app was used');
            
            // Status
            $table->boolean('is_public')->default(false)->comment('Publicly accessible (tenant-wide)');
            $table->boolean('is_exportable')->default(true)->comment('Can be exported as standalone HTML');
            
            // Timestamps
            $table->timestamps();
            $table->softDeletes();
            
            // Indexes (OS3.5 Performance Excellence)
            $table->index('app_id', 'idx_generated_apps_app_id');
            $table->index('conversation_id', 'idx_generated_apps_conversation');
            $table->index('user_id', 'idx_generated_apps_user');
            $table->index(['tenant_id', 'is_public'], 'idx_generated_apps_tenant_public');
            $table->index('app_type', 'idx_generated_apps_type');
            $table->index('last_used_at', 'idx_generated_apps_last_used');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('generated_apps');
    }
};

