"""
Pattern per query di COMPARAZIONE - Domande che richiedono confronti
Organizzati per tipo di confronto e operatore comparativo
"""

# Lista completa ed esaustiva di pattern per query comparative
COMPARISON_QUERY_PATTERNS = [
    # — CONFRONTI DIRETTI —
    "confronta",
    "confrontare",
    "confrontami",
    "confronta tra",
    "confronta con",
    "confronto tra",
    "confronto con",
    "confronto di",
    "metti a confronto",
    "fai un confronto",
    "effettua un confronto",
    "esegui un confronto",
    "voglio confrontare",
    "vorrei confrontare",
    "puoi confrontare",
    "potresti confrontare",
    
    # — DIFFERENZE —
    "differenza",
    "differenze",
    "differenza tra",
    "differenza di",
    "differenze tra",
    "differenze di",
    "che differenza",
    "quali differenze",
    "quale differenza",
    "che differenza c'è",
    "quali differenze ci sono",
    "dimmi la differenza",
    "dimmi le differenze",
    "mostrami la differenza",
    "mostrami le differenze",
    "spiega la differenza",
    "spiega le differenze",
    "indica la differenza",
    "indica le differenze",
    "in cosa differisce",
    "in cosa differiscono",
    "cosa cambia",
    "cosa cambia tra",
    "cosa cambia da",
    "come differisce",
    "come differiscono",
    
    # — SIMILITUDINI —
    "similitudine",
    "similitudini",
    "somiglianza",
    "somiglianze",
    "analogia",
    "analogie",
    "in comune",
    "cosa hanno in comune",
    "che hanno in comune",
    "quali sono le similitudini",
    "quali sono le somiglianze",
    "quali sono le analogie",
    "dimmi le similitudini",
    "dimmi le somiglianze",
    "cosa è simile",
    "cosa è analogo",
    "in cosa si assomigliano",
    "in che modo si assomigliano",
    
    # — OPERATORI: VS / VERSUS —
    "vs",
    "vs.",
    "versus",
    "contro",
    "o",
    " o ",
    "oppure",
    "meglio",
    "peggio",
    "preferibile",
    
    # — OPERATORI: RISPETTO A —
    "rispetto a",
    "rispetto al",
    "rispetto alla",
    "rispetto ai",
    "rispetto alle",
    "in confronto a",
    "in confronto al",
    "in confronto alla",
    "in confronto ai",
    "in confronto alle",
    "paragonato a",
    "paragonato al",
    "paragonato alla",
    "paragonati ai",
    "paragonate alle",
    "comparato a",
    "comparato al",
    "comparato alla",
    "comparati ai",
    "comparate alle",
    "a confronto con",
    "a paragone di",
    "in rapporto a",
    "in relazione a",
    
    # — COMPARATIVI: MAGGIORANZA —
    "più",
    "più di",
    "più del",
    "più della",
    "più dei",
    "più delle",
    "più che",
    "maggiore",
    "maggiore di",
    "maggiore del",
    "maggiore della",
    "maggiori di",
    "maggiori dei",
    "maggiori delle",
    "superiore",
    "superiore a",
    "superiore al",
    "superiore alla",
    "superiori a",
    "superiori ai",
    "superiori alle",
    "oltre",
    "oltre a",
    "oltre il",
    "oltre la",
    "sopra",
    "sopra a",
    "sopra il",
    "sopra la",
    "al di sopra",
    "più alto",
    "più alta",
    "più alti",
    "più alte",
    "più grande",
    "più grandi",
    "più lungo",
    "più lunga",
    "più lunghi",
    "più lunghe",
    
    # — COMPARATIVI: MINORANZA —
    "meno",
    "meno di",
    "meno del",
    "meno della",
    "meno dei",
    "meno delle",
    "meno che",
    "minore",
    "minore di",
    "minore del",
    "minore della",
    "minori di",
    "minori dei",
    "minori delle",
    "inferiore",
    "inferiore a",
    "inferiore al",
    "inferiore alla",
    "inferiori a",
    "inferiori ai",
    "inferiori alle",
    "sotto",
    "sotto a",
    "sotto il",
    "sotto la",
    "al di sotto",
    "più basso",
    "più bassa",
    "più bassi",
    "più basse",
    "più piccolo",
    "più piccola",
    "più piccoli",
    "più piccole",
    "più corto",
    "più corta",
    "più corti",
    "più corte",
    
    # — COMPARATIVI: UGUAGLIANZA —
    "uguale",
    "uguali",
    "uguale a",
    "uguali a",
    "uguale al",
    "uguale alla",
    "uguali ai",
    "uguali alle",
    "stesso",
    "stessa",
    "stessi",
    "stesse",
    "lo stesso di",
    "la stessa di",
    "gli stessi di",
    "le stesse di",
    "identico",
    "identica",
    "identici",
    "identiche",
    "pari a",
    "pari al",
    "pari alla",
    "tanto quanto",
    "così come",
    "come",
    
    # — SUPERLATIVI —
    "il più",
    "la più",
    "i più",
    "le più",
    "il meno",
    "la meno",
    "i meno",
    "le meno",
    "il migliore",
    "la migliore",
    "i migliori",
    "le migliori",
    "il peggiore",
    "la peggiore",
    "i peggiori",
    "le peggiori",
    "il maggiore",
    "la maggiore",
    "i maggiori",
    "le maggiori",
    "il minore",
    "la minore",
    "i minori",
    "le minori",
    "il massimo",
    "la massima",
    "i massimi",
    "le massime",
    "il minimo",
    "la minima",
    "i minimi",
    "le minime",
    "il primo",
    "la prima",
    "i primi",
    "le prime",
    "l'ultimo",
    "l'ultima",
    "gli ultimi",
    "le ultime",
    
    # — DOMANDE COMPARATIVE —
    "quale è meglio",
    "quale è migliore",
    "quale è peggiore",
    "quale è più",
    "quale è meno",
    "quale costa più",
    "quale costa meno",
    "quale vale più",
    "quale vale meno",
    "quale dura più",
    "quale dura meno",
    "quale è più grande",
    "quale è più piccolo",
    "quale è più lungo",
    "quale è più corto",
    "quale è più veloce",
    "quale è più lento",
    "chi è più",
    "chi è meno",
    "cosa è più",
    "cosa è meno",
    "dove è più",
    "dove è meno",
    
    # — PREFERENZE COMPARATIVE —
    "preferisci",
    "preferibile",
    "preferenza",
    "meglio",
    "meglio di",
    "meglio che",
    "è meglio",
    "sarebbe meglio",
    "peggio",
    "peggio di",
    "peggio che",
    "è peggio",
    "sarebbe peggio",
    "conviene",
    "conviene più",
    "è più conveniente",
    "vantaggioso",
    "più vantaggioso",
    "svantaggioso",
    "più svantaggioso",
    
    # — RANKING E CLASSIFICHE —
    "classifica",
    "classifiche",
    "ordina",
    "ordinare",
    "ordinami",
    "ordine",
    "in ordine",
    "ordine di",
    "dal più",
    "dal meno",
    "dalla più",
    "dalla meno",
    "dai più",
    "dai meno",
    "dalle più",
    "dalle meno",
    "crescente",
    "decrescente",
    "top",
    "top 10",
    "primi 10",
    "ultimi 10",
    "migliori",
    "peggiori",
    
    # — RAPPORTI COMPARATIVI —
    "quanto più",
    "quanto meno",
    "di quanto",
    "di quanti",
    "di quante",
    "quanto maggiore",
    "quanto minore",
    "quanto superiore",
    "quanto inferiore",
    "in che misura",
    "di che entità",
    
    # — ALTERNATIVE E SCELTE —
    "alternativa",
    "alternative",
    "alternativa a",
    "alternative a",
    "o",
    "oppure",
    "piuttosto che",
    "invece di",
    "al posto di",
    "in sostituzione di",
    "sostituire con",
    "sostituire",
    "rimpiazzare",
    "scegliere tra",
    "scelta tra",
]

# Set minimale greedy per fallback rapido
COMPARISON_QUERY_MINIMAL_PATTERNS = [
    # Confronti base
    "confronta",
    "confronto",
    "differenza",
    
    # Operatori
    "vs",
    "versus",
    "rispetto a",
    "rispetto al",
    
    # Comparativi
    "più",
    "meno",
    "maggiore",
    "minore",
    "superiore",
    "inferiore",
    "migliore",
    "peggiore",
    
    # Uguaglianza
    "uguale",
    "stesso",
    
    # Domande
    "quale è meglio",
    "quale è più",
    "quale costa",
    
    # Ranking
    "classifica",
    "ordina",
    "top",
]
