"""
Conversational Query Patterns - Pattern per riconoscere query conversazionali/saluti
Questi pattern identificano domande conversazionali che non richiedono documenti
"""

# Query CONVERSAZIONALI - Lista completa
CONVERSATIONAL_QUERY_PATTERNS = [
    # — SALUTI —
    "ciao",
    "ciao come stai",
    "ciao come va",
    "ci sei",
    "ci sei ancora",
    "ci sei là",
    "ci sei lì",
    "ehi",
    "hey",
    "salve",
    "buongiorno",
    "buon giorno",
    "buonasera",
    "buona sera",
    "buonanotte",
    "buona notte",
    "buon pomeriggio",
    "saluti",

    # — CORTESIE E RINGRAZIAMENTI —
    "grazie",
    "grazie mille",
    "grazie infinite",
    "grazie tante",
    "ti ringrazio",
    "ti ringrazio molto",
    "mille grazie",
    "prego",
    "di nulla",
    "figurati",
    "ok",
    "okay",
    "okey",
    "va bene",
    "va benissimo",
    "perfetto",
    "perfetto grazie",
    "ottimo",
    "benissimo",
    "d'accordo",

    # — STATO E BENESSERE —
    "come stai",
    "come va",
    "come va oggi",
    "come ti va",
    "tutto bene",
    "tutto ok",
    "tutto a posto",
    "va tutto bene",
    "stai bene",
    "come ti senti",
    "come procede",

    # — RICHIESTE DI AIUTO GENERICHE —
    "aiuto",
    "aiutami",
    "aiutami per favore",
    "puoi aiutarmi",
    "mi aiuti",
    "help",
    "ho bisogno di aiuto",
    "serve aiuto",

    # — DOMANDE SUL SISTEMA/ASSISTENTE —
    "sai",
    "sai fare",
    "sai come",
    "sai cosa",
    "puoi",
    "puoi fare",
    "puoi dirmi",
    "puoi spiegarmi",
    "puoi aiutarmi",
    "vuoi",
    "vuoi fare",
    "vuoi dirmi",
    "fai",
    "cosa fai",
    "cosa sai fare",
    "cosa puoi fare",
    "che fai",
    "che cosa fai",
    "conosci",
    "conosci il",
    "conosci la",
    "ti piace",
    "ti piacciono",
    "ti piace fare",

    # — CAPACITÀ SPECIFICHE DEL SISTEMA —
    "sai ballare",
    "sai cantare",
    "sai suonare",
    "sai guidare",
    "sai cucinare",
    "sai nuotare",
    "puoi ballare",
    "puoi cantare",
    "puoi suonare",
    "puoi guidare",
    "puoi cucinare",
    "puoi nuotare",

    # — DESIDERI E CONDIZIONALI —
    "ti va",
    "ti va di",
    "ti andrebbe",
    "ti andrebbe di",
    "vorresti",
    "vorresti fare",
    "potresti",
    "potresti fare",
    "potresti dirmi",
    "saresti",
    "saresti in grado",

    # — IDENTITÀ DEL SISTEMA —
    "chi sei",
    "cosa sei",
    "chi sei tu",
    "cosa sei tu",
    "dove sei",
    "dove ti trovi",
    "come sei fatto",
    "come sei fatta",
    "sei un robot",
    "sei un'intelligenza artificiale",
    "sei un'ai",
    "sei una macchina",
    "sei umano",
    "sei umana",

    # — PREFERENZE DEL SISTEMA —
    "cosa ti piace",
    "cosa non ti piace",
    "cosa preferisci",
    "preferisci",
    "qual è il tuo preferito",
    "qual è la tua preferita",

    # — OPINIONI E PENSIERI —
    "che ne pensi",
    "cosa ne pensi",
    "cosa pensi di",
    "qual è la tua opinione",
    "qual è il tuo parere",
    "secondo te",
    "a tuo parere",
    "a tuo avviso",

    # — SCUSE E DISPIACERI —
    "scusa",
    "scusami",
    "scusate",
    "chiedo scusa",
    "perdono",
    "perdonami",
    "mi dispiace",
    "mi spiace",

    # — RICHIESTE NARRATIVE —
    "dimmi",
    "dimmi qualcosa",
    "dimmi tu",
    "raccontami",
    "raccontami qualcosa",
    "raccontami una storia",
    "parlami",
    "parlami di te",
    "parlami un po'",

    # — INCOMPRENSIONI —
    "non so",
    "non lo so",
    "non capisco",
    "non ho capito",
    "non comprendo",
    "spiegami",
    "spiegamelo",
    "cosa significa",
    "cosa significa per te",
    "cosa vuol dire",
    "cosa intendi",

    # — METAFORE E IDIOMI —
    "ago in un pagliaio",
    "ago nel pagliaio",
    "ago in pagliaio",
    "cercare un ago",
    "cercare l'ago",
    "troppo difficile",
    "troppo complicato",
    "impossibile trovare",
    "impossibile da trovare",
    "come cercare",
    "è come",
    "è come cercare",
    "sembra impossibile",
    "missione impossibile",
    "introvabile",
    "cercare l'introvabile",

    # — CONFERME E NEGAZIONI —
    "sì",
    "si",
    "certo",
    "certamente",
    "sicuro",
    "sicuramente",
    "esatto",
    "esattamente",
    "proprio così",
    "no",
    "nope",
    "nah",
    "assolutamente no",
    "per niente",
    "neanche per sogno",

    # — ADDII E CHIUSURE —
    "arrivederci",
    "addio",
    "a presto",
    "ci vediamo",
    "ci sentiamo",
    "alla prossima",
    "buona giornata",
    "buona serata",
    "buona notte",
    "stammi bene",
    "ciao ciao",
]

# Query CONVERSAZIONALI - MINIMAL PATTERN SET (fallback greedy)
CONVERSATIONAL_QUERY_MINIMAL_PATTERNS = [
    "ciao",
    "grazie",
    "come stai",
    "come va",
    "aiuto",
    "chi sei",
    "cosa sei",
    "sai",
    "puoi",
    "vuoi",
    "ti piace",
    "che ne pensi",
    "scusa",
    "dimmi",
    "raccontami",
]
