"""
Pattern per query di DEFINIZIONE - Domande che chiedono significati, spiegazioni, concetti
Organizzati per tipo di richiesta definitoria
"""

# Lista completa ed esaustiva di pattern per query di definizione
DEFINITION_QUERY_PATTERNS = [
    # — RICHIESTE DI DEFINIZIONE BASE —
    "cos'è",
    "cos è",
    "cosa è",
    "cosa sono",
    "che cos'è",
    "che cos è",
    "che cosa è",
    "che cosa sono",
    "definizione",
    "definizione di",
    "definisci",
    "definire",
    "definiscimi",
    "dimmi cos'è",
    "dimmi cosa è",
    "dimmi cosa sono",
    "spiega cos'è",
    "spiega cosa è",
    "spiega cosa sono",
    "che significa",
    "che cosa significa",
    "cosa significa",
    "cosa significano",
    
    # — SIGNIFICATI —
    "significato",
    "significato di",
    "significato del",
    "significato della",
    "significato dei",
    "significato delle",
    "significa",
    "significano",
    "vuol dire",
    "vuole dire",
    "vogliono dire",
    "cosa vuol dire",
    "cosa vuole dire",
    "cosa vogliono dire",
    "che vuol dire",
    "che vuole dire",
    "che vogliono dire",
    "qual è il significato",
    "quali sono i significati",
    "dammi il significato",
    "fornisci il significato",
    
    # — SPIEGAZIONI —
    "spiega",
    "spiegare",
    "spiegami",
    "spiega il",
    "spiega la",
    "spiega i",
    "spiega le",
    "spiegazione",
    "spiegazione di",
    "spiegazione del",
    "spiegazione della",
    "spiegazione dei",
    "spiegazione delle",
    "dammi una spiegazione",
    "fornisci una spiegazione",
    "voglio una spiegazione",
    "vorrei una spiegazione",
    "puoi spiegare",
    "puoi spiegarmi",
    "potresti spiegare",
    "potresti spiegarmi",
    
    # — CHIARIMENTI —
    "chiarisci",
    "chiarire",
    "chiariscimi",
    "chiarimento",
    "chiarimento su",
    "chiarimenti su",
    "dammi un chiarimento",
    "fornisci un chiarimento",
    "voglio un chiarimento",
    "vorrei un chiarimento",
    "puoi chiarire",
    "puoi chiarirmi",
    "potresti chiarire",
    "potresti chiarirmi",
    "chiaro",
    "non è chiaro",
    "non mi è chiaro",
    "rendilo chiaro",
    
    # — CONCETTI —
    "concetto",
    "concetto di",
    "concetto del",
    "concetto della",
    "concetti",
    "concetti di",
    "qual è il concetto",
    "quali sono i concetti",
    "spiega il concetto",
    "spiega i concetti",
    "illustra il concetto",
    "illustra i concetti",
    
    # — DESCRIZIONI —
    "descri",
    "descrivi",
    "descrivere",
    "descrivimi",
    "descrizione",
    "descrizione di",
    "descrizione del",
    "descrizione della",
    "descrizione dei",
    "descrizione delle",
    "dammi una descrizione",
    "fornisci una descrizione",
    "voglio una descrizione",
    "vorrei una descrizione",
    "in cosa consiste",
    "di cosa si tratta",
    "cosa si intende",
    "cosa si intende per",
    
    # — TERMINI E PAROLE —
    "termine",
    "termine di",
    "termini",
    "termini di",
    "parola",
    "parole",
    "vocabolo",
    "vocaboli",
    "espressione",
    "espressioni",
    "che termine è",
    "che parola è",
    "cosa indica il termine",
    "cosa indica la parola",
    "cosa indica l'espressione",
    
    # — SPIEGAZIONI SEMPLICI —
    "spiega in parole semplici",
    "spiegami in modo semplice",
    "in parole semplici",
    "in modo semplice",
    "in termini semplici",
    "semplicemente",
    "spiegazione semplice",
    "definizione semplice",
    "come se avessi 5 anni",
    "come se fossi un bambino",
    "per un principiante",
    "per chi non sa",
    
    # — SPIEGAZIONI TECNICHE —
    "spiegazione tecnica",
    "definizione tecnica",
    "in termini tecnici",
    "tecnicamente",
    "dal punto di vista tecnico",
    "a livello tecnico",
    "dettagli tecnici",
    
    # — NATURA E ESSENZA —
    "natura",
    "natura di",
    "natura del",
    "natura della",
    "qual è la natura",
    "di che natura",
    "essenza",
    "essenza di",
    "essenza del",
    "essenza della",
    "qual è l'essenza",
    "sostanza",
    "sostanza di",
    "in sostanza",
    
    # — IDENTIFICAZIONE —
    "identifica",
    "identificare",
    "identificami",
    "identificazione",
    "cosa identifica",
    "cosa identificano",
    "che tipo di",
    "che genere di",
    "che categoria",
    "che classe",
    "rientra",
    "rientra in",
    "appartiene a",
    "fa parte di",
    
    # — SCOPO E FUNZIONE —
    "a cosa serve",
    "a che serve",
    "a cosa servono",
    "a che servono",
    "qual è lo scopo",
    "quale scopo",
    "quali scopi",
    "funzione",
    "funzione di",
    "funzioni di",
    "qual è la funzione",
    "quali sono le funzioni",
    "come funziona",
    "come funzionano",
    "funzionamento",
    "funzionamento di",
    "finalità",
    "finalità di",
    "qual è la finalità",
    "obiettivo",
    "obiettivo di",
    "qual è l'obiettivo",
    
    # — CARATTERISTICHE —
    "caratteristica",
    "caratteristiche",
    "caratteristica di",
    "caratteristiche di",
    "quali sono le caratteristiche",
    "dimmi le caratteristiche",
    "quali caratteristiche",
    "che caratteristiche",
    "peculiarità",
    "peculiarità di",
    "aspetti",
    "aspetti di",
    "quali aspetti",
    "proprietà",
    "proprietà di",
    "quali proprietà",
    
    # — TIPOLOGIE E CLASSIFICAZIONI —
    "tipologia",
    "tipologie",
    "tipo",
    "tipi",
    "tipo di",
    "tipi di",
    "quali tipi",
    "che tipo",
    "categoria",
    "categorie",
    "categoria di",
    "quali categorie",
    "che categoria",
    "classe",
    "classi",
    "classe di",
    "quali classi",
    "che classe",
    "genere",
    "generi",
    "genere di",
    "quali generi",
    "che genere",
    
    # — ESEMPI E ILLUSTRAZIONI —
    "esempio",
    "esempi",
    "esempio di",
    "esempi di",
    "fammi un esempio",
    "dammi un esempio",
    "dammi degli esempi",
    "fornisci un esempio",
    "fornisci esempi",
    "quali sono esempi",
    "ad esempio",
    "per esempio",
    "illustra con esempi",
    "illustrazione",
    "illustrami",
    
    # — DIFFERENZE DEFINITORIE —
    "in che senso",
    "che senso ha",
    "che intendi per",
    "cosa intendi per",
    "cosa intendete per",
    "cosa si intende con",
    "cosa si intende quando",
    "quando si parla di",
    "quando si dice",
    
    # — CONTESTO E AMBITO —
    "in che contesto",
    "in quale contesto",
    "contesto",
    "contesto di",
    "ambito",
    "ambito di",
    "in che ambito",
    "in quale ambito",
    "campo",
    "campo di",
    "in che campo",
    "settore",
    "settore di",
    "in che settore",
    
    # — ACRONIMI E SIGLE —
    "acronimo",
    "acronimo di",
    "cosa significa l'acronimo",
    "sigla",
    "sigla di",
    "cosa significa la sigla",
    "sta per",
    "cosa sta per",
    "abbreviazione",
    "abbreviazione di",
]

# Set minimale greedy per fallback rapido
DEFINITION_QUERY_MINIMAL_PATTERNS = [
    # Base
    "cos'è",
    "cosa è",
    "cosa sono",
    "definizione",
    "definisci",
    
    # Significato
    "significa",
    "significato",
    "vuol dire",
    
    # Spiegazione
    "spiega",
    "spiegami",
    "spiegazione",
    
    # Descrizione
    "descrivi",
    "descrizione",
    "di cosa si tratta",
    
    # Funzione
    "a cosa serve",
    "funzione",
    "come funziona",
    
    # Caratteristiche
    "caratteristiche",
    "proprietà",
    
    # Tipologie
    "tipo",
    "categoria",
    "genere",
    
    # Esempi
    "esempio",
    "esempi",
]
