"""
Pattern per query di FACT CHECK - Domande fattuali che richiedono verifica
Organizzati per tipo di interrogativa e contesto
"""

# Lista completa ed esaustiva di pattern per fact check queries
FACT_CHECK_QUERY_PATTERNS = [
    # — INTERROGATIVI BASE: QUANDO —
    "quando",
    "quando è",
    "quando era",
    "quando fu",
    "quando sono",
    "quando erano",
    "quando furono",
    "quando viene",
    "quando veniva",
    "quando verrà",
    "quando si è",
    "quando si era",
    "quando si terrà",
    "quando si tiene",
    "quando si teneva",
    "quando avviene",
    "quando avveniva",
    "quando avverrà",
    "quando è stato",
    "quando è stata",
    "quando sono stati",
    "quando sono state",
    "da quando",
    "fino a quando",
    "entro quando",
    "per quando",
    "in che anno",
    "in che mese",
    "in che giorno",
    "in che data",
    "in quale anno",
    "in quale mese",
    "in quale giorno",
    "in quale data",
    "a che ora",
    "in che periodo",
    "in quale periodo",
    "in che epoca",
    "in quale epoca",
    
    # — INTERROGATIVI BASE: DOVE —
    "dove",
    "dove è",
    "dove era",
    "dove si trova",
    "dove si trovava",
    "dove si troverà",
    "dove sono",
    "dove erano",
    "dove si tengono",
    "dove si tenevano",
    "dove avviene",
    "dove avveniva",
    "dove sta",
    "dove stava",
    "dove stanno",
    "dove stavano",
    "dove abita",
    "dove abitava",
    "dove vive",
    "dove viveva",
    "dove lavora",
    "dove lavorava",
    "dove si svolge",
    "dove si svolgeva",
    "dove è situato",
    "dove è situata",
    "dove è ubicato",
    "dove è ubicata",
    "in che luogo",
    "in quale luogo",
    "in che posto",
    "in quale posto",
    "in che città",
    "in quale città",
    "in che paese",
    "in quale paese",
    "in che regione",
    "in quale regione",
    "in che zona",
    "in quale zona",
    
    # — INTERROGATIVI BASE: CHI —
    "chi",
    "chi è",
    "chi era",
    "chi fu",
    "chi sono",
    "chi erano",
    "chi furono",
    "chi ha",
    "chi aveva",
    "chi avrà",
    "chi fa",
    "chi faceva",
    "chi farà",
    "chi dice",
    "chi diceva",
    "chi ha detto",
    "chi ha fatto",
    "chi ha scritto",
    "chi ha inventato",
    "chi ha scoperto",
    "chi ha fondato",
    "chi ha creato",
    "chi ha vinto",
    "chi ha perso",
    "chi governa",
    "chi governava",
    "chi dirige",
    "chi dirigeva",
    "chi comanda",
    "chi comandava",
    "chi decide",
    "chi decideva",
    "chi partecipa",
    "chi partecipava",
    "chi è stato",
    "chi è stata",
    "chi sono stati",
    "chi sono state",
    "di chi",
    "a chi",
    "con chi",
    "per chi",
    "da chi",
    
    # — INTERROGATIVI BASE: COSA/CHE COSA —
    "cosa",
    "che cosa",
    "cos'è",
    "cosa è",
    "cosa era",
    "cosa fu",
    "cosa sono",
    "cosa erano",
    "cosa significa",
    "cosa significava",
    "cosa vuol dire",
    "cosa voleva dire",
    "cosa rappresenta",
    "cosa rappresentava",
    "cosa indica",
    "cosa indicava",
    "cosa prevede",
    "cosa prevedeva",
    "cosa stabilisce",
    "cosa stabiliva",
    "cosa dice",
    "cosa diceva",
    "cosa contiene",
    "cosa conteneva",
    "cosa include",
    "cosa includeva",
    "cosa comprende",
    "cosa comprendeva",
    "cosa fa",
    "cosa faceva",
    "cosa farà",
    "cosa succede",
    "cosa succedeva",
    "cosa succederà",
    "cosa accade",
    "cosa accadeva",
    "cosa accadrà",
    "cosa avviene",
    "cosa avveniva",
    "cosa avverrà",
    "di cosa",
    "a cosa",
    "con cosa",
    "per cosa",
    "da cosa",
    
    # — INTERROGATIVI BASE: QUALE/QUALI —
    "quale",
    "quali",
    "quale è",
    "quale era",
    "quali sono",
    "quali erano",
    "quale sarebbe",
    "quali sarebbero",
    "qual è",
    "qual era",
    "in quale",
    "in quali",
    "con quale",
    "con quali",
    "per quale",
    "per quali",
    "da quale",
    "da quali",
    "a quale",
    "a quali",
    
    # — INTERROGATIVI COMPOSTI —
    "in che modo",
    "in quale modo",
    "in che maniera",
    "in quale maniera",
    "con quale metodo",
    "con quali metodi",
    "attraverso quale",
    "attraverso quali",
    "mediante quale",
    "mediante quali",
    
    # — RICHIESTE DI FATTI SPECIFICI —
    "dimmi quando",
    "dimmi dove",
    "dimmi chi",
    "dimmi cosa",
    "dimmi quale",
    "dimmi quali",
    "dimmi in che",
    "dimmi il nome",
    "dimmi la data",
    "dimmi il luogo",
    "dammi il nome",
    "dammi la data",
    "dammi il luogo",
    "dammi i nomi",
    "dammi le date",
    "dammi i luoghi",
    "fornisci il nome",
    "fornisci la data",
    "fornisci il luogo",
    "indica il nome",
    "indica la data",
    "indica il luogo",
    "specifica quando",
    "specifica dove",
    "specifica chi",
    "specifica cosa",
    
    # — VERIFICA FATTI —
    "è vero che",
    "è vero",
    "è corretto che",
    "è corretto",
    "è esatto che",
    "è esatto",
    "confermi che",
    "conferma che",
    "verifica che",
    "verifica se",
    "controlla che",
    "controlla se",
    "è successo che",
    "è accaduto che",
    "è avvenuto che",
    "ha avuto luogo",
    "si è verificato",
    "si è svolto",
    "c'è stato",
    "ci sono stati",
    "c'è stata",
    "ci sono state",
    
    # — DOMANDE SU ESISTENZA —
    "esiste",
    "esistono",
    "esisteva",
    "esistevano",
    "c'è",
    "ci sono",
    "c'era",
    "c'erano",
    "vi è",
    "vi sono",
    "vi era",
    "vi erano",
    "è presente",
    "sono presenti",
    "era presente",
    "erano presenti",
    
    # — RICHIESTE DI INFORMAZIONI DOCUMENTALI —
    "secondo il",
    "secondo la",
    "secondo i",
    "secondo le",
    "in base al",
    "in base alla",
    "in base ai",
    "in base alle",
    "sulla base del",
    "sulla base della",
    "sulla base dei",
    "sulla base delle",
    "come previsto dal",
    "come previsto dalla",
    "come previsto dai",
    "come previsto dalle",
    "come stabilito dal",
    "come stabilito dalla",
    "come indicato nel",
    "come indicato nella",
    "come riportato nel",
    "come riportato nella",
    "come scritto nel",
    "come scritto nella",
    "come specificato nel",
    "come specificato nella",
    
    # — RICHIESTE DI DETTAGLI —
    "quali sono i dettagli",
    "quali sono le informazioni",
    "quali sono i dati",
    "dammi i dettagli",
    "dammi le informazioni",
    "dammi i dati",
    "fornisci i dettagli",
    "fornisci le informazioni",
    "fornisci i dati",
    "elenca i dettagli",
    "elenca le informazioni",
    "elenca i dati",
    "mostrami i dettagli",
    "mostrami le informazioni",
    "mostrami i dati",
    
    # — RICHIESTE DI ELENCHI FATTUALI —
    "elenca",
    "elencare",
    "elencami",
    "elenca tutti",
    "elenca tutte",
    "dammi l'elenco",
    "dammi la lista",
    "fornisci l'elenco",
    "fornisci la lista",
    "mostrami l'elenco",
    "mostrami la lista",
    "quali sono",
    "quanti sono",
    "quante sono",
]

# Set minimale greedy per fallback rapido
FACT_CHECK_QUERY_MINIMAL_PATTERNS = [
    # Interrogativi base
    "quando",
    "dove",
    "chi",
    "cosa",
    "che cosa",
    "cos'è",
    "quale",
    "quali",
    "qual è",
    "quanti",
    "quante",
    "quanto",
    
    # Verifica fatti
    "è vero",
    "è corretto",
    "confermi",
    "verifica",
    
    # Esistenza
    "esiste",
    "esistono",
    "c'è",
    "ci sono",
    
    # Richieste informazioni
    "dimmi quando",
    "dimmi dove",
    "dimmi chi",
    "dimmi cosa",
    "secondo",
    "in base a",
    
    # Elenchi
    "elenca",
    "elenco",
    "lista",
]
