"""
Generative Query Patterns - Pattern per riconoscere query generative/creative
Questi pattern identificano domande che richiedono creazione/generazione di contenuti
"""

# Query GENERATIVE/CREATIVE - Lista completa
GENERATIVE_QUERY_PATTERNS = [
    # — VERBI DI CREAZIONE —
    "crea",
    "creare",
    "crea un",
    "crea una",
    "creami",
    "creami un",
    "creami una",
    "genera",
    "generare",
    "genera un",
    "genera una",
    "generami",
    "generami un",
    "generami una",
    "scrivi",
    "scrivere",
    "scrivi un",
    "scrivi una",
    "scrivimi",
    "scrivimi un",
    "scrivimi una",
    "redigi",
    "redigere",
    "redigi un",
    "redigi una",
    "componi",
    "comporre",
    "componi un",
    "componi una",
    "elabora",
    "elaborare",
    "elabora un",
    "elabora una",
    "sviluppa",
    "sviluppare",
    "sviluppa un",
    "sviluppa una",
    "costruisci",
    "costruire",
    "costruisci un",
    "costruisci una",
    "formula",
    "formulare",
    "formula un",
    "formula una",
    "progetta",
    "progettare",
    "progetta un",
    "progetta una",
    "disegna",
    "disegnare",
    "disegna un",
    "disegna una",
    "prepara",
    "preparare",
    "prepara un",
    "prepara una",
    "preparami",
    "preparami un",
    "preparami una",
    "produci",
    "producere",
    "produci un",
    "produci una",

    # — RICHIESTE DI IDEE/SUGGERIMENTI —
    "dammi idee",
    "dammi delle idee",
    "dammi alcune idee",
    "dammi qualche idea",
    "suggerisci",
    "suggeriscimi",
    "suggerisci delle",
    "suggerisci alcuni",
    "suggerisci alcune",
    "proponi",
    "proponimi",
    "proponi delle",
    "proponi alcuni",
    "proponi alcune",
    "consiglia",
    "consigliami",
    "consiglia delle",
    "consiglia alcuni",
    "consiglia alcune",
    "raccomanda",
    "raccomandami",
    "raccomanda delle",
    "raccomanda alcuni",
    "raccomanda alcune",
    "elenca possibili",
    "elenca delle possibili",
    "elenca alcuni possibili",
    "elenca alcune possibili",
    "quali strategie",
    "quali sono le strategie",
    "quali approcci",
    "quali sono gli approcci",
    "quali metodi",
    "quali sono i metodi",
    "quali soluzioni",
    "quali sono le soluzioni",
    "quali alternative",
    "quali sono le alternative",
    "quali opzioni",
    "quali sono le opzioni",
    "che strategie",
    "che approcci",
    "che metodi",
    "che soluzioni",
    "che alternative",
    "che opzioni",

    # — STRUTTURE/FRAMEWORKS —
    "matrice",
    "una matrice",
    "la matrice",
    "delle matrici",
    "framework",
    "un framework",
    "il framework",
    "dei framework",
    "schema",
    "uno schema",
    "lo schema",
    "degli schemi",
    "template",
    "un template",
    "il template",
    "dei template",
    "modello",
    "un modello",
    "il modello",
    "dei modelli",
    "struttura",
    "una struttura",
    "la struttura",
    "delle strutture",
    "tabella",
    "una tabella",
    "la tabella",
    "delle tabelle",
    "griglia",
    "una griglia",
    "la griglia",
    "delle griglie",
    "diagramma",
    "un diagramma",
    "il diagramma",
    "dei diagrammi",
    "piano",
    "un piano",
    "il piano",
    "dei piani",
    "roadmap",
    "una roadmap",
    "la roadmap",
    "delle roadmap",
    "mappa",
    "una mappa",
    "la mappa",
    "delle mappe",
    "checklist",
    "una checklist",
    "la checklist",
    "delle checklist",
    "lista di controllo",
    "elenco puntato",
    "un elenco",

    # — ORGANIZZAZIONE/PIANIFICAZIONE —
    "come posso organizzare",
    "come potrei organizzare",
    "come organizzare",
    "come devo organizzare",
    "aiutami ad organizzare",
    "aiutami a organizzare",
    "come posso strutturare",
    "come potrei strutturare",
    "come strutturare",
    "come devo strutturare",
    "aiutami a strutturare",
    "come impostare",
    "come posso impostare",
    "come potrei impostare",
    "come devo impostare",
    "aiutami ad impostare",
    "pianifica",
    "pianificare",
    "pianifica un",
    "pianifica una",
    "aiutami a pianificare",
    "organizza",
    "organizzare",
    "organizza un",
    "organizza una",
    "struttura",
    "strutturare",
    "struttura un",
    "struttura una",
    "imposta",
    "impostare",
    "imposta un",
    "imposta una",
    "configura",
    "configurare",
    "configura un",
    "configura una",

    # — ANALISI E SINTESI CREATIVE —
    "sintetizza in",
    "sintetizzami",
    "fai una sintesi",
    "riassumi in modo creativo",
    "riassumi con",
    "traduci in",
    "trasforma in",
    "converti in",
    "adatta per",
    "rielabora",
    "rielabora in",
    "riscrivi",
    "riscrivi in",
    "riscrivi come",
    "riscrivi per",

    # — BRAINSTORMING —
    "brainstorming",
    "brainstorming su",
    "brainstorming per",
    "facciamo brainstorming",
    "aiutami con un brainstorming",
    "sessione di brainstorming",
    "idee creative",
    "idee innovative",
    "soluzioni creative",
    "soluzioni innovative",
    "approcci creativi",
    "approcci innovativi",

    # — DECISIONI E PRIORITIZZAZIONE —
    "prioritizza",
    "prioritizzare",
    "aiutami a prioritizzare",
    "come prioritizzare",
    "come posso prioritizzare",
    "metti in ordine di priorità",
    "ordina per priorità",
    "ordina per importanza",
    "classifica per priorità",
    "classifica per importanza",
    "quali priorità",
    "quali sono le priorità",
    "stabilisci le priorità",
    "stabilisci un ordine",
    "definisci le priorità",
]

# Query GENERATIVE - MINIMAL PATTERN SET (fallback greedy)
GENERATIVE_QUERY_MINIMAL_PATTERNS = [
    "crea",
    "genera",
    "scrivi",
    "elabora",
    "sviluppa",
    "progetta",
    "suggerisci",
    "proponi",
    "matrice",
    "framework",
    "schema",
    "tabella",
    "piano",
    "roadmap",
    "pianifica",
    "organizza",
    "prioritizza",
]
