"""
Pattern per query di INTERPRETAZIONE - Domande che chiedono spiegazioni del "perché", motivazioni, ragioni
Organizzati per tipo di richiesta interpretativa
"""

# Lista completa ed esaustiva di pattern per query interpretative
INTERPRETATION_QUERY_PATTERNS = [
    # — PERCHÉ E CAUSALI —
    "perché",
    "per che",
    "perchè",
    "per quale motivo",
    "per qual motivo",
    "per quale ragione",
    "per qual ragione",
    "per che motivo",
    "per che ragione",
    "come mai",
    "come è possibile",
    "come è possibile che",
    "come mai è",
    "come mai sono",
    "per cosa",
    "per cosa è",
    "per cosa sono",
    
    # — MOTIVI E RAGIONI —
    "motivo",
    "motivi",
    "motivo di",
    "motivo del",
    "motivo della",
    "motivi di",
    "motivi del",
    "motivi della",
    "qual è il motivo",
    "quali sono i motivi",
    "dimmi il motivo",
    "dimmi i motivi",
    "spiega il motivo",
    "spiega i motivi",
    "quali motivi",
    "che motivo",
    "che motivi",
    "ragione",
    "ragioni",
    "ragione di",
    "ragione del",
    "ragione della",
    "ragioni di",
    "qual è la ragione",
    "quali sono le ragioni",
    "dimmi la ragione",
    "dimmi le ragioni",
    "spiega la ragione",
    "spiega le ragioni",
    "quali ragioni",
    "che ragione",
    "che ragioni",
    
    # — CAUSE E CONSEGUENZE —
    "causa",
    "cause",
    "causa di",
    "causa del",
    "causa della",
    "cause di",
    "qual è la causa",
    "quali sono le cause",
    "dimmi la causa",
    "dimmi le cause",
    "a causa di",
    "causato da",
    "causata da",
    "causati da",
    "causate da",
    "dovuto a",
    "dovuta a",
    "dovuti a",
    "dovute a",
    "dipende da",
    "dipendente da",
    "deriva da",
    "derivato da",
    "derivata da",
    "derivanti da",
    "conseguenza",
    "conseguenze",
    "in conseguenza",
    "come conseguenza",
    
    # — FINALITÀ E SCOPI —
    "finalità",
    "finalità di",
    "finalità del",
    "finalità della",
    "qual è la finalità",
    "quali sono le finalità",
    "scopo",
    "scopi",
    "scopo di",
    "scopo del",
    "scopo della",
    "qual è lo scopo",
    "quali sono gli scopi",
    "a che scopo",
    "con che scopo",
    "con quale scopo",
    "allo scopo di",
    "obiettivo",
    "obiettivi",
    "obiettivo di",
    "obiettivo del",
    "qual è l'obiettivo",
    "quali sono gli obiettivi",
    "fine",
    "fini",
    "fine di",
    "al fine di",
    "a che fine",
    "con che fine",
    
    # — SPIEGAZIONI E GIUSTIFICAZIONI —
    "spiega perché",
    "spiegami perché",
    "spiega il perché",
    "spiegazione del perché",
    "giustifica",
    "giustificare",
    "giustificami",
    "giustificazione",
    "giustificazione di",
    "qual è la giustificazione",
    "dimmi la giustificazione",
    "motivazione",
    "motivazioni",
    "motivazione di",
    "qual è la motivazione",
    "quali sono le motivazioni",
    "dimmi la motivazione",
    
    # — ORIGINI E FONTI —
    "origine",
    "origini",
    "origine di",
    "origine del",
    "origine della",
    "qual è l'origine",
    "quali sono le origini",
    "da dove viene",
    "da dove deriva",
    "da dove nasce",
    "da cosa deriva",
    "da cosa nasce",
    "da cosa proviene",
    "provenienza",
    "fonte",
    "fonti",
    "radice",
    "radici",
    "alla radice di",
    "alle radici di",
    
    # — IMPLICAZIONI E SIGNIFICATI —
    "implicazione",
    "implicazioni",
    "cosa implica",
    "cosa implicano",
    "quali implicazioni",
    "implicazioni di",
    "questo implica",
    "questo comporta",
    "comporta",
    "comportano",
    "significa che",
    "significano che",
    "vuol dire che",
    "vogliono dire che",
    "cosa significa che",
    "cosa vuol dire che",
    
    # — INTERPRETAZIONI E LETTURE —
    "interpretazione",
    "interpretazioni",
    "come interpretare",
    "come si interpreta",
    "interpretare",
    "come va interpretato",
    "come va interpretata",
    "come leggere",
    "come si legge",
    "lettura",
    "lettura di",
    "chiave di lettura",
    "senso",
    "senso di",
    "che senso ha",
    "quale senso ha",
    "in che senso",
    "in quale senso",
    
    # — FATTORI E ELEMENTI —
    "fattore",
    "fattori",
    "quali fattori",
    "che fattori",
    "fattori che",
    "elemento",
    "elementi",
    "quali elementi",
    "che elementi",
    "elementi che",
    "aspetto",
    "aspetti",
    "quali aspetti",
    "componente",
    "componenti",
    "quali componenti",
    
    # — CONDIZIONI E CIRCOSTANZE —
    "condizione",
    "condizioni",
    "quali condizioni",
    "in quali condizioni",
    "a quali condizioni",
    "sotto quali condizioni",
    "circostanza",
    "circostanze",
    "quali circostanze",
    "in quali circostanze",
    "situazione",
    "situazioni",
    "in quale situazione",
    "contesto",
    "in che contesto",
    "nel contesto di",
    
    # — NECESSITÀ E OBBLIGHI —
    "necessario",
    "necessaria",
    "necessari",
    "necessarie",
    "è necessario",
    "sono necessari",
    "necessità",
    "necessità di",
    "per necessità",
    "bisogno",
    "bisogno di",
    "c'è bisogno",
    "obbligo",
    "obblighi",
    "obbligatorio",
    "obbligatoria",
    "obbligatori",
    "obbligatorie",
    "è obbligatorio",
    "sono obbligatori",
    
    # — UTILITÀ E IMPORTANZA —
    "utilità",
    "utilità di",
    "utile",
    "utile per",
    "a cosa è utile",
    "a che è utile",
    "importanza",
    "importanza di",
    "importante",
    "importante per",
    "perché è importante",
    "rilevanza",
    "rilevante",
    "rilevante per",
    "significativo",
    "significativa",
    "significativi",
    "significative",
    
    # — VANTAGGI E SVANTAGGI —
    "vantaggio",
    "vantaggi",
    "quali vantaggi",
    "che vantaggi",
    "vantaggi di",
    "perché conviene",
    "convenienza",
    "svantaggio",
    "svantaggi",
    "quali svantaggi",
    "che svantaggi",
    "svantaggi di",
    "perché non conviene",
    "inconveniente",
    "inconvenienti",
    "problema",
    "problemi",
    "quali problemi",
    "problematica",
    "problematiche",
    
    # — EFFETTI E IMPATTI —
    "effetto",
    "effetti",
    "quali effetti",
    "che effetto",
    "che effetti",
    "effetto di",
    "effetti di",
    "impatto",
    "impatti",
    "quale impatto",
    "quali impatti",
    "impatto di",
    "conseguenza",
    "conseguenze",
    "quali conseguenze",
    "ripercussione",
    "ripercussioni",
    "risultato",
    "risultati",
    
    # — FUNZIONAMENTO E MECCANISMI —
    "come funziona",
    "come funzionano",
    "funzionamento",
    "funzionamento di",
    "meccanismo",
    "meccanismi",
    "quale meccanismo",
    "quali meccanismi",
    "dinamica",
    "dinamiche",
    "quali dinamiche",
    "logica",
    "logica di",
    "quale logica",
    "principio",
    "principi",
    "quale principio",
    "quali principi",
    "su quale principio",
    
    # — RELAZIONI E CONNESSIONI —
    "relazione",
    "relazioni",
    "quale relazione",
    "quali relazioni",
    "relazione tra",
    "relazione con",
    "collegamento",
    "collegamenti",
    "collegamento tra",
    "collegamento con",
    "connessione",
    "connessioni",
    "connessione tra",
    "nesso",
    "nessi",
    "nesso tra",
    "legame",
    "legami",
    "legame tra",
    "rapporto",
    "rapporti",
    "rapporto tra",
    "rapporto con",
    
    # — GIUDIZI E VALUTAZIONI —
    "giudizio",
    "giudizi",
    "tuo giudizio",
    "tua valutazione",
    "opinione",
    "opinioni",
    "tua opinione",
    "tue opinioni",
    "parere",
    "tuo parere",
    "valutazione",
    "valutazioni",
    "considerazione",
    "considerazioni",
    "tue considerazioni",
    "punto di vista",
    "tuo punto di vista",
    "prospettiva",
    "tua prospettiva",
    
    # — DOMANDE RETORICHE E RIFLESSIVE —
    "a cosa serve",
    "a che serve",
    "che senso ha",
    "quale senso ha",
    "ha senso",
    "non ha senso",
    "come si spiega",
    "come si giustifica",
    "si può spiegare",
    "si può giustificare",
]

# Set minimale greedy per fallback rapido
INTERPRETATION_QUERY_MINIMAL_PATTERNS = [
    # Base
    "perché",
    "come mai",
    
    # Motivi
    "motivo",
    "ragione",
    "causa",
    
    # Scopi
    "scopo",
    "finalità",
    "obiettivo",
    
    # Spiegazioni
    "spiega perché",
    "giustificazione",
    "motivazione",
    
    # Origini
    "origine",
    "da dove",
    
    # Implicazioni
    "implica",
    "significa che",
    
    # Interpretazioni
    "interpretazione",
    "senso",
    
    # Fattori
    "fattori",
    "elementi",
    
    # Condizioni
    "condizioni",
    "circostanze",
    
    # Utilità
    "a cosa serve",
    "utilità",
    "importanza",
    
    # Effetti
    "effetti",
    "impatto",
    "conseguenze",
]
