"""
Pattern per query NUMERICHE - Domande che richiedono valori quantitativi
Organizzati per tipo di quantità e operazione matematica
"""

# Lista completa ed esaustiva di pattern per query numeriche
NUMERICAL_QUERY_PATTERNS = [
    # — INTERROGATIVI QUANTITATIVI BASE —
    "quanto",
    "quanta",
    "quanti",
    "quante",
    "quanto è",
    "quanto era",
    "quanto sarà",
    "quanta è",
    "quanta era",
    "quanta sarà",
    "quanti sono",
    "quanti erano",
    "quanti saranno",
    "quante sono",
    "quante erano",
    "quante saranno",
    "quanto costa",
    "quanto costava",
    "quanto costerà",
    "quanto vale",
    "quanto valeva",
    "quanto varrà",
    "quanto misura",
    "quanto misurava",
    "quanto pesa",
    "quanto pesava",
    "quanto dura",
    "quanto durava",
    "quanto tempo",
    "quanta distanza",
    "quanto dista",
    "quanto distava",
    
    # — RICHIESTE DI NUMERI/CIFRE —
    "dammi il numero",
    "dammi la cifra",
    "dammi il valore",
    "dammi l'importo",
    "dammi la quantità",
    "fornisci il numero",
    "fornisci la cifra",
    "fornisci il valore",
    "fornisci l'importo",
    "fornisci la quantità",
    "indica il numero",
    "indica la cifra",
    "indica il valore",
    "indica l'importo",
    "indica la quantità",
    "specifica il numero",
    "specifica la cifra",
    "specifica il valore",
    "specifica l'importo",
    "specifica la quantità",
    "qual è il numero",
    "qual è la cifra",
    "qual è il valore",
    "qual è l'importo",
    "qual è la quantità",
    "qual è l'ammontare",
    
    # — OPERAZIONI MATEMATICHE: SOMMA/TOTALE —
    "somma",
    "somma di",
    "somma dei",
    "somma delle",
    "somma totale",
    "totale",
    "totale di",
    "totale dei",
    "totale delle",
    "totale complessivo",
    "importo totale",
    "importo complessivo",
    "ammontare totale",
    "ammontare complessivo",
    "valore totale",
    "valore complessivo",
    "quanto in totale",
    "quanti in totale",
    "quante in totale",
    "quanta in totale",
    "calcola il totale",
    "calcola la somma",
    "calcola l'importo",
    "dimmi il totale",
    "dimmi la somma",
    "qual è il totale",
    "qual è la somma",
    "a quanto ammonta",
    "a quanto ammontano",
    
    # — OPERAZIONI MATEMATICHE: DIFFERENZA/SOTTRAZIONE —
    "differenza",
    "differenza tra",
    "differenza di",
    "scarto",
    "scarto tra",
    "quanto di più",
    "quanto di meno",
    "quanto in più",
    "quanto in meno",
    "quanti di più",
    "quanti di meno",
    "quanti in più",
    "quanti in meno",
    "di quanto",
    "di quanti",
    "di quante",
    
    # — OPERAZIONI MATEMATICHE: MEDIA —
    "media",
    "media di",
    "media dei",
    "media delle",
    "valore medio",
    "importo medio",
    "costo medio",
    "prezzo medio",
    "quanto in media",
    "quanti in media",
    "quante in media",
    "calcola la media",
    "qual è la media",
    
    # — PERCENTUALI —
    "percentuale",
    "percentuale di",
    "percentuale dei",
    "percentuale delle",
    "che percentuale",
    "quale percentuale",
    "quanta percentuale",
    "quanto percento",
    "quanto per cento",
    "quanto %",
    "tasso",
    "tasso di",
    "quota",
    "quota di",
    "proporzione",
    "proporzione di",
    "rapporto percentuale",
    "in percentuale",
    "calcola la percentuale",
    "qual è la percentuale",
    
    # — RAPPORTI E PROPORZIONI —
    "rapporto",
    "rapporto tra",
    "rapporto di",
    "ratio",
    "proporzione",
    "proporzione tra",
    "quante volte",
    "quanto volte",
    "multiplo",
    "divisione",
    "divisione tra",
    "diviso",
    "diviso per",
    
    # — QUANTITÀ SPECIFICHE —
    "numero di",
    "numero dei",
    "numero delle",
    "quantità di",
    "quantità dei",
    "quantità delle",
    "cifra di",
    "cifra dei",
    "cifra delle",
    "conteggio",
    "conteggio di",
    "conteggio dei",
    "conteggio delle",
    "conta",
    "conta di",
    "conta dei",
    "conta delle",
    "quanti ne",
    "quante ne",
    
    # — DIMENSIONI E MISURE —
    "dimensione",
    "dimensioni",
    "misura",
    "misure",
    "grandezza",
    "lunghezza",
    "larghezza",
    "altezza",
    "profondità",
    "diametro",
    "raggio",
    "circonferenza",
    "perimetro",
    "area",
    "superficie",
    "volume",
    "capacità",
    "peso",
    "massa",
    "quanto è grande",
    "quanto è lungo",
    "quanto è largo",
    "quanto è alto",
    "quanto è profondo",
    "quanto pesa",
    
    # — COSTI E PREZZI —
    "costo",
    "costo di",
    "costo dei",
    "costo delle",
    "prezzo",
    "prezzo di",
    "prezzo dei",
    "prezzo delle",
    "valore",
    "valore di",
    "valore dei",
    "valore delle",
    "importo",
    "importo di",
    "importo dei",
    "importo delle",
    "quanto costa",
    "quanto costano",
    "quanto vale",
    "quanto valgono",
    "a quanto costa",
    "a quanto costano",
    "prezzo unitario",
    "costo unitario",
    
    # — DISTANZE E DURATE —
    "distanza",
    "distanza da",
    "distanza tra",
    "lontananza",
    "quanto dista",
    "quanto distano",
    "quanti chilometri",
    "quanti metri",
    "quanti km",
    "durata",
    "durata di",
    "durata dei",
    "durata delle",
    "tempo",
    "tempo di",
    "tempo dei",
    "tempo delle",
    "quanto dura",
    "quanto durano",
    "quanto tempo",
    "quanti minuti",
    "quante ore",
    "quanti giorni",
    "quanti mesi",
    "quanti anni",
    
    # — INCREMENTI E VARIAZIONI —
    "aumento",
    "aumento di",
    "incremento",
    "incremento di",
    "crescita",
    "crescita di",
    "diminuzione",
    "diminuzione di",
    "decremento",
    "decremento di",
    "riduzione",
    "riduzione di",
    "variazione",
    "variazione di",
    "quanto è aumentato",
    "quanto è diminuito",
    "quanto è cresciuto",
    "quanto è calato",
    "di quanto è",
    
    # — LIMITI E SOGLIE —
    "limite",
    "limite di",
    "limite massimo",
    "limite minimo",
    "soglia",
    "soglia di",
    "massimo",
    "minimo",
    "tetto",
    "tetto di",
    "pavimento",
    "fino a quanto",
    "fino a quanti",
    "fino a quante",
    "non oltre",
    "non più di",
    "almeno",
    "al massimo",
    "al minimo",
    
    # — STATISTICHE E AGGREGAZIONI —
    "maggiore",
    "minore",
    "massimo",
    "minimo",
    "più alto",
    "più basso",
    "più grande",
    "più piccolo",
    "il più",
    "la più",
    "i più",
    "le più",
    "il maggiore",
    "il minore",
    "il massimo",
    "il minimo",
]

# Set minimale greedy per fallback rapido
NUMERICAL_QUERY_MINIMAL_PATTERNS = [
    # Interrogativi base
    "quanto",
    "quanta",
    "quanti",
    "quante",
    
    # Operazioni
    "somma",
    "totale",
    "differenza",
    "media",
    
    # Percentuali
    "percentuale",
    "%",
    "percento",
    
    # Quantità
    "numero di",
    "quantità",
    
    # Costi
    "costo",
    "prezzo",
    "vale",
    "costa",
    
    # Misure
    "misura",
    "dimensione",
    "peso",
    "lunghezza",
    
    # Tempo/Distanza
    "distanza",
    "durata",
    "tempo",
    
    # Statistiche
    "massimo",
    "minimo",
    "maggiore",
    "minore",
]
