"""
Personal Query Patterns - Pattern per riconoscere query personali dell'utente
Questi pattern identificano domande che richiedono recupero di memorie personali
"""

# Query PERSONALI UTENTE (memorie) - PRIORITÀ MASSIMA
PERSONAL_QUERY_PATTERNS = [
    # — IDENTITÀ BASE —
    "come mi chiamo",
    "chi sono",
    "chi sono io",
    "qual è il mio nome",
    "mi chiamo",
    "il mio nome",
    "il mio cognome",
    "come si scrive il mio nome",
    "ti ricordi come mi chiamo",
    "ti ricordi il mio nome",
    "parlami di me",
    "parlami di chi sono",
    "dimmi chi sono per te",
    "dimmi qualcosa su di me",
    "cosa sai di me",

    # — DATI ANAGRAFICI / ETÀ / NASCITA —
    "quanti anni ho",
    "che età ho",
    "la mia età",
    "quando sono nato",
    "data di nascita",
    "il mio compleanno",
    "che segno zodiacale sono",
    "sono nato a",
    "sono nato il",
    "il mio segno zodiacale",

    # — LUOGO / RESIDENZA / ORIGINI —
    "dove vivo",
    "dove abito",
    "la mia città",
    "mia città",
    "sulla mia città",
    "della mia città",
    "di più sulla mia città",
    "dimmi della mia città",
    "parlami della mia città",
    "la città dove vivo",
    "la città in cui abito",
    "la mia città natale",
    "da dove vengo",
    "sono di",
    "sono originario di",
    "il mio paese",
    "mio paese",
    "la mia regione",
    "mia regione",
    "il mio indirizzo",
    "il mio quartiere",
    "mio quartiere",
    "zona dove vivo",
    "vicino a casa mia",
    "casa mia",
    "mia casa",

    # — CONTATTI PERSONALI —
    "il mio numero di telefono",
    "il mio telefono",
    "il mio cellulare",
    "il mio contatto",
    "il mio contatto telefonico",
    "la mia email",
    "la mia mail",
    "il mio indirizzo email",
    "il mio account",
    "i miei contatti",

    # — LAVORO / PROFESSIONE / STUDIO —
    "il mio lavoro",
    "mio lavoro",
    "cosa faccio",
    "cosa faccio di lavoro",
    "faccio di lavoro",
    "che lavoro faccio",
    "che lavoro svolgo",
    "che lavoro ho",
    "la mia professione",
    "la mia carriera",
    "la mia posizione lavorativa",
    "il mio ruolo in azienda",
    "il mio capo",
    "i miei colleghi",
    "la mia azienda",
    "dove lavoro",
    "posto di lavoro",
    "ufficio dove lavoro",
    "sto cercando lavoro",
    "sto cambiando lavoro",
    "il mio curriculum",
    "il mio cv",
    "il mio percorso di studi",
    "la mia formazione",
    "la mia facoltà",
    "la mia scuola",
    "il mio titolo di studio",

    # — FAMIGLIA / RELAZIONI STRETTE —
    "mia moglie",
    "mio marito",
    "mia compagna",
    "mio compagno",
    "mia ragazza",
    "il mio ragazzo",
    "il mio partner",
    "il mio fidanzato",
    "la mia fidanzata",
    "mia famiglia",
    "mio figlio",
    "mia figlia",
    "miei figli",
    "i miei figli",
    "i miei genitori",
    "mio padre",
    "mio babbo",
    "mia madre",
    "mia mamma",
    "mio fratello",
    "mia sorella",
    "i miei fratelli",
    "le mie sorelle",
    "i miei nonni",
    "mia nonna",
    "mio nonno",
    "mio zio",
    "mia zia",
    "i miei cugini",
    "la mia famiglia allargata",

    # — RELAZIONI AFFETTIVE / STATO CIVILE —
    "sono single",
    "sono sposato",
    "sono sposata",
    "sono separato",
    "sono separata",
    "sono divorziato",
    "sono divorziata",
    "sono fidanzato",
    "sono fidanzata",
    "la mia relazione",
    "la mia storia",
    "la mia ex",
    "il mio ex",
    "la mia vita sentimentale",

    # — ANIMALI DOMESTICI —
    "il mio cane",
    "il mio gatto",
    "i miei animali",
    "il mio animale domestico",
    "i miei cani",
    "i miei gatti",

    # — GUSTI / PREFERENZE / INTERESSI —
    "mi piace",
    "mi piacciono",
    "mi piace molto",
    "mi piace tantissimo",
    "mi piace un sacco",
    "non mi piace",
    "non mi piacciono",
    "non mi piace per niente",
    "non mi piacciono per niente",
    "preferisco",
    "preferirei",
    "amo",
    "adoro",
    "vado pazzo per",
    "vado matto per",
    "detesto",
    "odio",
    "non sopporto",
    "mi interessa",
    "mi interessa molto",
    "mi interessa poco",
    "sono appassionato di",
    "sono appassionata di",
    "la mia passione",
    "le mie passioni",
    "i miei interessi",
    "il mio hobby",
    "i miei hobby",
    "nel tempo libero",
    "nel mio tempo libero",
    "nel weekend di solito",
    "di solito faccio",
    "la mia musica preferita",
    "il mio genere musicale preferito",
    "il mio film preferito",
    "la mia serie preferita",
    "il mio libro preferito",
    "il mio autore preferito",
    "il mio sport preferito",
    "la mia squadra del cuore",
    "il mio piatto preferito",
    "il mio cibo preferito",
    "la mia bevanda preferita",

    # — BISOGNI / NECESSITÀ PERSONALI —
    "mi serve",
    "mi servirebbe",
    "mi è utile",
    "mi sarebbe utile",
    "ho bisogno",
    "ho bisogno di",
    "avrei bisogno",
    "avrei bisogno di",
    "ho davvero bisogno",
    "mi manca",
    "mi mancano",
    "mi urge",
    "per me è importante",
    "per me è fondamentale",

    # — ABITUDINI / ROUTINE —
    "la mia routine",
    "la mia giornata tipo",
    "come passo le mie giornate",
    "di solito faccio",
    "di solito la mattina",
    "di solito la sera",
    "la mattina faccio",
    "la sera faccio",
    "nel weekend faccio",
    "le mie abitudini",
    "la mia vita quotidiana",

    # — CARATTERE / EMOZIONI / STATO INTERNO —
    "il mio carattere",
    "il mio modo di essere",
    "come sono fatto",
    "come sono fatta",
    "la mia personalità",
    "come mi sento",
    "mi sento spesso",
    "il mio umore",
    "i miei sentimenti",
    "le mie emozioni",
    "le mie paure",
    "le mie insicurezze",
    "le mie fragilità",
    "i miei punti di forza",
    "i miei punti deboli",
    "i miei difetti",
    "le mie qualità",

    # — SALUTE / BENESSERE (PERSONALISSIMI) —
    "la mia salute",
    "il mio stato di salute",
    "il mio medico",
    "il mio dottore",
    "le mie medicine",
    "le mie terapie",
    "sto poco bene",
    "non sto bene",
    "mi sento stanco",
    "mi sento stressato",
    "mi sento stressata",

    # — SOLDI / FINANZE PERSONALI —
    "i miei soldi",
    "le mie finanze",
    "la mia situazione economica",
    "la mia situazione finanziaria",
    "il mio conto in banca",
    "il mio conto corrente",
    "la mia carta di credito",
    "il mio stipendio",
    "quanto guadagno",
    "il mio reddito",
    "le mie spese",
    "le mie entrate",
    "le mie uscite",

    # — STRUMENTI / ACCOUNT PERSONALI —
    "il mio computer",
    "il mio pc",
    "il mio portatile",
    "il mio telefono",
    "il mio smartphone",
    "il mio account",
    "i miei account",
    "i miei profili social",
    "il mio profilo instagram",
    "il mio profilo facebook",
    "il mio profilo linkedin",

    # — STORIA PERSONALE / PASSATO —
    "la mia storia",
    "la mia storia personale",
    "la mia infanzia",
    "la mia adolescenza",
    "il mio passato",
    "la mia esperienza",
    "le mie esperienze",
    "le esperienze che ho fatto",
    "i miei ricordi",
    "i ricordi della mia vita",

    # — FUTURO / OBIETTIVI PERSONALI —
    "i miei progetti",
    "i miei obiettivi",
    "i miei sogni",
    "le mie ambizioni",
    "i miei piani per il futuro",
    "cosa voglio fare",
    "cosa voglio diventare",
    "cosa vorrei fare",
    "cosa vorrei diventare",

    # — FORMULAZIONI GENERICHE CON POSSESSIVI —
    "i miei",
    "le mie",
    "il mio",
    "la mia",
    "una cosa mia",
    "cose che mi riguardano",
    "che mi riguarda personalmente",
    "per la mia vita",
    "per me personalmente",
    "per la mia situazione",
    "riguardo a me",
    "su di me",
]

# Query PERSONALI UTENTE - MINIMAL PATTERN SET (fallback greedy)
# Pattern più larghi e generici per catch-all su query personali
# Usa questi quando i pattern specifici non matchano ma sospetti una query personale
PERSONAL_QUERY_MINIMAL_PATTERNS = [
    # — POSSESSIVI GENERICI —
    "mio",
    "mia",
    "miei",
    "mie",
    "il mio",
    "la mia",
    "i miei",
    "le mie",

    # — IDENTITÀ —
    "mi chiamo",
    "come mi chiamo",
    "chi sono",
    "il mio nome",

    # — LUOGO —
    "dove vivo",
    "dove abito",
    "mia città",
    "la mia città",

    # — LAVORO —
    "mio lavoro",
    "il mio lavoro",
    "cosa faccio di lavoro",

    # — FAMIGLIA —
    "mia moglie",
    "mio marito",
    "mia compagna",
    "mio compagno",
    "mio figlio",
    "mia figlia",
    "mia famiglia",

    # — GUSTI / PREFERENZE —
    "mi piace",
    "mi piacciono",
    "preferisco",
    "amo",
    "adoro",
    "odio",
    "detesto",

    # — BISOGNI / NECESSITÀ —
    "mi serve",
    "mi servirebbe",
    "ho bisogno",
    "avrei bisogno",

    # — INTERESSI / PASSIONI —
    "mi interessa",
    "mi interessano",
    "sono appassionato di",
    "sono appassionata di",

    # — FUTURO / OBIETTIVI —
    "i miei progetti",
    "i miei obiettivi",
    "i miei sogni",
]
