"""
Pattern per query PROCEDURALI - Domande su come fare qualcosa, procedure, istruzioni
Organizzati per tipo di richiesta procedurale
"""

# Lista completa ed esaustiva di pattern per query procedurali
PROCEDURE_QUERY_PATTERNS = [
    # — INTERROGATIVI BASE: COME —
    "come",
    "come si",
    "come si fa",
    "come si fanno",
    "come fare",
    "come faccio",
    "come faccio a",
    "come posso",
    "come posso fare",
    "come potrei",
    "come potrei fare",
    "come devo",
    "come devo fare",
    "come dovrei",
    "come dovrei fare",
    "come si può",
    "come si potrebbe",
    "come è possibile",
    "come sarebbe possibile",
    "in che modo",
    "in quale modo",
    "con che metodo",
    "con quale metodo",
    "con che mezzo",
    "con quali mezzi",
    
    # — PROCEDURE E PROCESSI —
    "procedura",
    "procedura per",
    "procedura di",
    "procedure",
    "procedure per",
    "procedure di",
    "qual è la procedura",
    "quali sono le procedure",
    "dimmi la procedura",
    "spiega la procedura",
    "illustra la procedura",
    "descrivi la procedura",
    "processo",
    "processo per",
    "processo di",
    "processi",
    "qual è il processo",
    "quali sono i processi",
    "dimmi il processo",
    "spiega il processo",
    "iter",
    "iter per",
    "iter di",
    "qual è l'iter",
    
    # — ISTRUZIONI E PASSAGGI —
    "istruzioni",
    "istruzioni per",
    "istruzioni di",
    "dammi le istruzioni",
    "fornisci le istruzioni",
    "quali sono le istruzioni",
    "passaggi",
    "passaggi per",
    "passaggi di",
    "quali sono i passaggi",
    "dammi i passaggi",
    "elenca i passaggi",
    "spiega i passaggi",
    "step",
    "step per",
    "step by step",
    "passo passo",
    "passo per passo",
    "passo dopo passo",
    "fase",
    "fasi",
    "fase per fase",
    "quali sono le fasi",
    "step da seguire",
    "passi da seguire",
    "fasi da seguire",
    
    # — GUIDE E TUTORIAL —
    "guida",
    "guida per",
    "guida su",
    "guide",
    "dammi una guida",
    "fornisci una guida",
    "tutorial",
    "tutorial per",
    "tutorial su",
    "manuale",
    "manuale per",
    "manuale di",
    "istruzioni d'uso",
    "istruzioni per l'uso",
    "modo d'uso",
    "modalità d'uso",
    
    # — METODI E TECNICHE —
    "metodo",
    "metodo per",
    "metodi",
    "metodi per",
    "qual è il metodo",
    "quali sono i metodi",
    "con che metodo",
    "con quale metodo",
    "tecnica",
    "tecnica per",
    "tecniche",
    "tecniche per",
    "qual è la tecnica",
    "quali sono le tecniche",
    "modalità",
    "modalità per",
    "modalità di",
    "qual è la modalità",
    "quali sono le modalità",
    "sistema",
    "sistema per",
    "modo",
    "modo per",
    "modo di",
    "modi per",
    "modi di",
    "in che modo",
    "in quale modo",
    
    # — REALIZZAZIONE E ESECUZIONE —
    "realizzare",
    "come realizzare",
    "per realizzare",
    "eseguire",
    "come eseguire",
    "per eseguire",
    "effettuare",
    "come effettuare",
    "per effettuare",
    "attuare",
    "come attuare",
    "implementare",
    "come implementare",
    "mettere in pratica",
    "come mettere in pratica",
    "portare a termine",
    "come portare a termine",
    "completare",
    "come completare",
    
    # — OTTENIMENTO E ACQUISIZIONE —
    "ottenere",
    "come ottenere",
    "per ottenere",
    "come si ottiene",
    "acquisire",
    "come acquisire",
    "per acquisire",
    "procurarsi",
    "come procurarsi",
    "come procurare",
    "reperire",
    "come reperire",
    "trovare",
    "come trovare",
    "dove trovare",
    "recuperare",
    "come recuperare",
    
    # — RICHIESTE E DOMANDE —
    "richiedere",
    "come richiedere",
    "per richiedere",
    "presentare richiesta",
    "come presentare richiesta",
    "fare richiesta",
    "come fare richiesta",
    "fare domanda",
    "come fare domanda",
    "presentare domanda",
    "come presentare domanda",
    "inoltrare",
    "come inoltrare",
    "inviare",
    "come inviare",
    
    # — ACCESSO E UTILIZZO —
    "accedere",
    "come accedere",
    "per accedere",
    "come si accede",
    "accesso",
    "accesso a",
    "utilizzare",
    "come utilizzare",
    "come si utilizza",
    "usare",
    "come usare",
    "come si usa",
    "uso",
    "uso di",
    "impiegare",
    "come impiegare",
    "servirsi",
    "come servirsi",
    "come ci si serve",
    
    # — ATTIVAZIONE E CONFIGURAZIONE —
    "attivare",
    "come attivare",
    "attivazione",
    "attivazione di",
    "configurare",
    "come configurare",
    "configurazione",
    "configurazione di",
    "impostare",
    "come impostare",
    "impostazione",
    "impostazioni",
    "settare",
    "come settare",
    "setting",
    "setup",
    "installare",
    "come installare",
    "installazione",
    "installazione di",
    
    # — MODIFICHE E CAMBIAMENTI —
    "modificare",
    "come modificare",
    "modifica",
    "modifica di",
    "cambiare",
    "come cambiare",
    "cambio",
    "cambio di",
    "variare",
    "come variare",
    "aggiornare",
    "come aggiornare",
    "aggiornamento",
    "aggiornamento di",
    "correggere",
    "come correggere",
    "correzione",
    "correzione di",
    
    # — RISOLUZIONE PROBLEMI —
    "risolvere",
    "come risolvere",
    "risoluzione",
    "risoluzione di",
    "risolvere il problema",
    "come risolvere il problema",
    "sistemare",
    "come sistemare",
    "riparare",
    "come riparare",
    "riparazione",
    "fixare",
    "come fixare",
    "fix",
    "come fare il fix",
    "debuggare",
    "come debuggare",
    "troubleshooting",
    
    # — VERIFICA E CONTROLLO —
    "verificare",
    "come verificare",
    "verifica",
    "verifica di",
    "controllare",
    "come controllare",
    "controllo",
    "controllo di",
    "checkare",
    "come checkare",
    "check",
    "monitorare",
    "come monitorare",
    "monitoraggio",
    "testare",
    "come testare",
    "test",
    "test di",
    
    # — CANCELLAZIONE E RIMOZIONE —
    "cancellare",
    "come cancellare",
    "cancellazione",
    "cancellazione di",
    "eliminare",
    "come eliminare",
    "eliminazione",
    "eliminazione di",
    "rimuovere",
    "come rimuovere",
    "rimozione",
    "rimozione di",
    "disattivare",
    "come disattivare",
    "disattivazione",
    "disinstallare",
    "come disinstallare",
    "disinstallazione",
    
    # — CREAZIONE E GENERAZIONE —
    "creare",
    "come creare",
    "creazione",
    "creazione di",
    "generare",
    "come generare",
    "generazione",
    "generazione di",
    "produrre",
    "come produrre",
    "produzione",
    "produzione di",
    "sviluppare",
    "come sviluppare",
    "sviluppo",
    "sviluppo di",
    
    # — REGISTRAZIONE E ISCRIZIONE —
    "registrare",
    "come registrare",
    "come registrarsi",
    "registrazione",
    "iscrivere",
    "come iscrivere",
    "come iscriversi",
    "iscrizione",
    "aprire un account",
    "come aprire un account",
    "creare un account",
    "come creare un account",
    
    # — COMUNICAZIONE E CONTATTO —
    "contattare",
    "come contattare",
    "comunicare",
    "come comunicare",
    "comunicazione",
    "come fare comunicazione",
    "notificare",
    "come notificare",
    "notifica",
    "segnalare",
    "come segnalare",
    "segnalazione",
    
    # — SEQUENZE CONDIZIONALI —
    "cosa fare se",
    "cosa devo fare se",
    "come comportarsi se",
    "come procedere se",
    "in caso di",
    "nel caso in cui",
    "qualora",
    "se dovesse",
    "se si verifica",
    "quando si verifica",
]

# Set minimale greedy per fallback rapido
PROCEDURE_QUERY_MINIMAL_PATTERNS = [
    # Base
    "come",
    "come si",
    "come fare",
    "come faccio",
    "come posso",
    
    # Procedura
    "procedura",
    "processo",
    "iter",
    
    # Istruzioni
    "istruzioni",
    "passaggi",
    "step",
    "passo",
    
    # Guide
    "guida",
    "tutorial",
    "manuale",
    
    # Metodi
    "metodo",
    "tecnica",
    "modalità",
    
    # Azioni comuni
    "ottenere",
    "richiedere",
    "accedere",
    "utilizzare",
    "usare",
    "attivare",
    "configurare",
    "installare",
    "modificare",
    "risolvere",
    "verificare",
    "cancellare",
    "creare",
    "registrarsi",
]
