"""
Pattern per query SPAZIALI - Domande su ubicazione, posizione, luogo, direzioni
Organizzati per tipo di riferimento spaziale
"""

# Lista completa ed esaustiva di pattern per query spaziali
SPATIAL_QUERY_PATTERNS = [
    # — INTERROGATIVI SPAZIALI BASE —
    "dove",
    "dove è",
    "dove era",
    "dove sarà",
    "dove sono",
    "dove erano",
    "dove saranno",
    "dove si trova",
    "dove si trovava",
    "dove si troverà",
    "dove si tengono",
    "dove si teneva",
    "dove si terrà",
    "dove sta",
    "dove stava",
    "dove stanno",
    "dove stavano",
    "dove si svolge",
    "dove si svolgeva",
    "dove si svolgerà",
    "in che luogo",
    "in quale luogo",
    "in che posto",
    "in quale posto",
    
    # — POSIZIONE E UBICAZIONE —
    "posizione",
    "posizioni",
    "posizione di",
    "posizione del",
    "posizione della",
    "qual è la posizione",
    "quali sono le posizioni",
    "dimmi la posizione",
    "indica la posizione",
    "ubicazione",
    "ubicazioni",
    "ubicazione di",
    "ubicazione del",
    "ubicazione della",
    "qual è l'ubicazione",
    "quali sono le ubicazioni",
    "dimmi l'ubicazione",
    "collocazione",
    "collocazione di",
    "situato",
    "situata",
    "situati",
    "situate",
    "dove è situato",
    "dove è situata",
    "dove sono situati",
    "dove sono situate",
    "è situato",
    "è situata",
    "sono situati",
    "sono situate",
    "ubicato",
    "ubicata",
    "ubicati",
    "ubicate",
    "dove è ubicato",
    "dove è ubicata",
    
    # — LUOGO E LOCALITÀ —
    "luogo",
    "luoghi",
    "luogo di",
    "luogo del",
    "luogo della",
    "in che luogo",
    "in quale luogo",
    "qual è il luogo",
    "quali sono i luoghi",
    "dimmi il luogo",
    "indica il luogo",
    "località",
    "località di",
    "in che località",
    "in quale località",
    "posto",
    "posti",
    "in che posto",
    "in quale posto",
    "che posto",
    "quale posto",
    "quali posti",
    "zona",
    "zone",
    "in che zona",
    "in quale zona",
    "che zona",
    "quale zona",
    "quali zone",
    "area",
    "aree",
    "in che area",
    "in quale area",
    "settore",
    "settori",
    "in che settore",
    
    # — CITTÀ E PAESI —
    "città",
    "in che città",
    "in quale città",
    "che città",
    "quale città",
    "quali città",
    "nella città",
    "nella città di",
    "paese",
    "paesi",
    "in che paese",
    "in quale paese",
    "che paese",
    "quale paese",
    "quali paesi",
    "nel paese",
    "comune",
    "comuni",
    "in che comune",
    "in quale comune",
    "nel comune",
    "municipio",
    "nel municipio",
    
    # — REGIONI E PROVINCE —
    "regione",
    "regioni",
    "in che regione",
    "in quale regione",
    "che regione",
    "quale regione",
    "quali regioni",
    "nella regione",
    "provincia",
    "province",
    "in che provincia",
    "in quale provincia",
    "che provincia",
    "quale provincia",
    "nella provincia",
    
    # — STATI E NAZIONI —
    "stato",
    "stati",
    "in che stato",
    "in quale stato",
    "che stato",
    "quale stato",
    "nello stato",
    "nazione",
    "nazioni",
    "in che nazione",
    "in quale nazione",
    "nella nazione",
    "paese",
    "nel paese",
    
    # — CONTINENTI —
    "continente",
    "continenti",
    "in che continente",
    "in quale continente",
    "nel continente",
    "quale continente",
    
    # — INDIRIZZI E VIE —
    "indirizzo",
    "indirizzi",
    "qual è l'indirizzo",
    "quali sono gli indirizzi",
    "dimmi l'indirizzo",
    "via",
    "vie",
    "in che via",
    "in quale via",
    "che via",
    "quale via",
    "nella via",
    "strada",
    "strade",
    "in che strada",
    "in quale strada",
    "nella strada",
    "corso",
    "corsi",
    "viale",
    "viali",
    "piazza",
    "piazze",
    "in piazza",
    "in che piazza",
    "largo",
    "vicolo",
    
    # — COORDINATE E RIFERIMENTI —
    "coordinate",
    "coordinate di",
    "quali sono le coordinate",
    "latitudine",
    "longitudine",
    "GPS",
    "coordinate GPS",
    "georeferenziazione",
    "punto GPS",
    "mappa",
    "sulla mappa",
    "nella mappa",
    
    # — DISTANZE —
    "distanza",
    "distanze",
    "distanza da",
    "distanza tra",
    "distanza di",
    "qual è la distanza",
    "quali sono le distanze",
    "dimmi la distanza",
    "quanto dista",
    "quanto distano",
    "quanti chilometri",
    "quanti metri",
    "quanti km",
    "lontananza",
    "lontano",
    "lontano da",
    "lontani da",
    "quanto lontano",
    "quanto è lontano",
    "vicino",
    "vicino a",
    "vicini a",
    "vicina a",
    "vicine a",
    "quanto vicino",
    "vicinanza",
    "prossimità",
    "in prossimità di",
    "nelle vicinanze",
    "nelle vicinanze di",
    
    # — DIREZIONI E ORIENTAMENTI —
    "direzione",
    "direzioni",
    "in che direzione",
    "in quale direzione",
    "che direzione",
    "quale direzione",
    "verso dove",
    "verso quale",
    "orientamento",
    "orientato",
    "orientata",
    "rivolto",
    "rivolta",
    "esposto",
    "esposta",
    "esposizione",
    
    # — PUNTI CARDINALI —
    "nord",
    "a nord",
    "verso nord",
    "a nord di",
    "settentrionale",
    "parte settentrionale",
    "sud",
    "a sud",
    "verso sud",
    "a sud di",
    "meridionale",
    "parte meridionale",
    "est",
    "a est",
    "verso est",
    "a est di",
    "orientale",
    "parte orientale",
    "ovest",
    "a ovest",
    "verso ovest",
    "a ovest di",
    "occidentale",
    "parte occidentale",
    "nord-est",
    "nord-ovest",
    "sud-est",
    "sud-ovest",
    
    # — RELAZIONI SPAZIALI: SOPRA/SOTTO —
    "sopra",
    "sopra a",
    "sopra il",
    "sopra la",
    "al di sopra",
    "al di sopra di",
    "sovrastante",
    "sotto",
    "sotto a",
    "sotto il",
    "sotto la",
    "al di sotto",
    "al di sotto di",
    "sottostante",
    "superiore",
    "inferiore",
    "piano superiore",
    "piano inferiore",
    
    # — RELAZIONI SPAZIALI: DENTRO/FUORI —
    "dentro",
    "dentro a",
    "dentro il",
    "dentro la",
    "all'interno",
    "all'interno di",
    "interno",
    "parte interna",
    "fuori",
    "fuori da",
    "fuori dal",
    "fuori dalla",
    "all'esterno",
    "all'esterno di",
    "esterno",
    "parte esterna",
    
    # — RELAZIONI SPAZIALI: ACCANTO/TRA —
    "accanto",
    "accanto a",
    "accanto al",
    "accanto alla",
    "di fianco",
    "di fianco a",
    "a fianco",
    "a fianco di",
    "laterale",
    "lato",
    "a lato di",
    "tra",
    "tra il",
    "tra la",
    "fra",
    "in mezzo",
    "in mezzo a",
    "nel mezzo",
    
    # — RELAZIONI SPAZIALI: DAVANTI/DIETRO —
    "davanti",
    "davanti a",
    "di fronte",
    "di fronte a",
    "frontale",
    "anteriore",
    "parte anteriore",
    "dietro",
    "dietro a",
    "dietro il",
    "dietro la",
    "posteriore",
    "parte posteriore",
    "retro",
    "sul retro",
    
    # — RELAZIONI SPAZIALI: CENTRO/PERIFERIA —
    "centro",
    "al centro",
    "al centro di",
    "nel centro",
    "centrale",
    "parte centrale",
    "zona centrale",
    "periferia",
    "in periferia",
    "nella periferia",
    "periferico",
    "periferica",
    "zona periferica",
    
    # — CONFINI E LIMITI SPAZIALI —
    "confine",
    "confini",
    "al confine",
    "sul confine",
    "oltre il confine",
    "limite",
    "limiti",
    "limite territoriale",
    "territorio",
    "territori",
    "nel territorio",
    "territorio di",
    "giurisdizione",
    "giurisdizione di",
    
    # — PIANI E LIVELLI —
    "piano",
    "piani",
    "a che piano",
    "a quale piano",
    "su che piano",
    "su quale piano",
    "al piano",
    "livello",
    "livelli",
    "a che livello",
    "a quale livello",
    "su che livello",
    "piano terra",
    "primo piano",
    "secondo piano",
    "piano interrato",
    "seminterrato",
    
    # — EDIFICI E STRUTTURE —
    "edificio",
    "edifici",
    "in che edificio",
    "in quale edificio",
    "nell'edificio",
    "palazzo",
    "palazzi",
    "nel palazzo",
    "stabile",
    "nello stabile",
    "struttura",
    "strutture",
    "nella struttura",
    
    # — AMBIENTI E SPAZI —
    "ambiente",
    "ambienti",
    "in che ambiente",
    "nell'ambiente",
    "spazio",
    "spazi",
    "in che spazio",
    "nello spazio",
    "sala",
    "sale",
    "in che sala",
    "in quale sala",
    "nella sala",
    "stanza",
    "stanze",
    "in che stanza",
    "nella stanza",
    "locale",
    "locali",
    "nel locale",
    "nei locali",
    
    # — SEDE E DOMICILIO —
    "sede",
    "sedi",
    "sede di",
    "sede del",
    "sede della",
    "qual è la sede",
    "quali sono le sedi",
    "presso la sede",
    "domicilio",
    "domicilio di",
    "residenza",
    "residenza di",
    "recapito",
    "recapiti",
]

# Set minimale greedy per fallback rapido
SPATIAL_QUERY_MINIMAL_PATTERNS = [
    # Base
    "dove",
    "dove si trova",
    "dove si tengono",
    
    # Posizione
    "posizione",
    "ubicazione",
    "situato",
    
    # Luogo
    "luogo",
    "località",
    "zona",
    
    # Geografici
    "città",
    "paese",
    "regione",
    "provincia",
    
    # Indirizzo
    "indirizzo",
    "via",
    "strada",
    
    # Distanza
    "distanza",
    "quanto dista",
    "lontano",
    "vicino",
    
    # Direzioni
    "direzione",
    "nord",
    "sud",
    "est",
    "ovest",
    
    # Relazioni spaziali
    "sopra",
    "sotto",
    "dentro",
    "fuori",
    "accanto",
    "davanti",
    "dietro",
    "centro",
    
    # Strutture
    "piano",
    "edificio",
    "sede",
]
