"""
Pattern per query TEMPORALI - Domande su tempo, date, periodi, cronologia
Organizzati per tipo di riferimento temporale
"""

# Lista completa ed esaustiva di pattern per query temporali
TEMPORAL_QUERY_PATTERNS = [
    # — INTERROGATIVI TEMPORALI BASE —
    "quando",
    "quando è",
    "quando era",
    "quando fu",
    "quando sono",
    "quando erano",
    "quando furono",
    "quando sarà",
    "quando saranno",
    "quando avviene",
    "quando avveniva",
    "quando avverrà",
    "quando si è",
    "quando si era",
    "quando si sarà",
    "quando si tiene",
    "quando si teneva",
    "quando si terrà",
    "da quando",
    "fino a quando",
    "entro quando",
    "per quando",
    "a quando",
    
    # — DATE E GIORNI —
    "data",
    "date",
    "data di",
    "data del",
    "data della",
    "qual è la data",
    "quali sono le date",
    "dimmi la data",
    "dammi la data",
    "fornisci la data",
    "indica la data",
    "specifica la data",
    "in che data",
    "in quale data",
    "a che data",
    "giorno",
    "giorni",
    "in che giorno",
    "in quale giorno",
    "che giorno",
    "quale giorno",
    "quali giorni",
    
    # — ANNI —
    "anno",
    "anni",
    "in che anno",
    "in quale anno",
    "che anno",
    "quale anno",
    "quali anni",
    "nell'anno",
    "negli anni",
    "durante l'anno",
    "durante gli anni",
    "nell'arco dell'anno",
    "nell'arco degli anni",
    
    # — MESI —
    "mese",
    "mesi",
    "in che mese",
    "in quale mese",
    "che mese",
    "quale mese",
    "quali mesi",
    "nel mese",
    "nei mesi",
    "durante il mese",
    "durante i mesi",
    
    # — SETTIMANE —
    "settimana",
    "settimane",
    "in che settimana",
    "in quale settimana",
    "che settimana",
    "quale settimana",
    "questa settimana",
    "la prossima settimana",
    "la settimana prossima",
    "la scorsa settimana",
    "la settimana scorsa",
    
    # — ORE E ORARI —
    "ora",
    "ore",
    "a che ora",
    "a quale ora",
    "che ora",
    "quale ora",
    "quali ore",
    "all'ora",
    "alle ore",
    "orario",
    "orari",
    "che orario",
    "quale orario",
    "quali orari",
    "in che orario",
    "in quale orario",
    
    # — PERIODI —
    "periodo",
    "periodi",
    "in che periodo",
    "in quale periodo",
    "che periodo",
    "quale periodo",
    "quali periodi",
    "durante il periodo",
    "durante i periodi",
    "nel periodo",
    "nei periodi",
    "arco temporale",
    "intervallo",
    "intervallo di tempo",
    "lasso di tempo",
    "nell'intervallo",
    
    # — EPOCHE E ERE —
    "epoca",
    "epoche",
    "in che epoca",
    "in quale epoca",
    "che epoca",
    "quale epoca",
    "durante l'epoca",
    "nell'epoca",
    "era",
    "ere",
    "età",
    "secolo",
    "secoli",
    "in che secolo",
    "nel secolo",
    "millennio",
    
    # — INIZIO E FINE —
    "inizio",
    "inizio di",
    "inizio del",
    "inizio della",
    "all'inizio",
    "all'inizio di",
    "all'inizio del",
    "dall'inizio",
    "dal principio",
    "inizia",
    "inizia il",
    "inizia la",
    "iniziano",
    "comincia",
    "cominciano",
    "parte",
    "partono",
    "fine",
    "fine di",
    "fine del",
    "fine della",
    "alla fine",
    "alla fine di",
    "alla fine del",
    "finisce",
    "finisce il",
    "finisce la",
    "finiscono",
    "termina",
    "terminano",
    "conclusione",
    "scadenza",
    "scadenze",
    "termine",
    "termine di",
    
    # — DURATA —
    "durata",
    "durata di",
    "durata del",
    "durata della",
    "quanto dura",
    "quanto durano",
    "per quanto tempo",
    "per quanto",
    "per quanti giorni",
    "per quanti mesi",
    "per quanti anni",
    "lunghezza",
    "lunghezza di",
    "estensione temporale",
    
    # — FREQUENZA —
    "frequenza",
    "ogni quanto",
    "ogni quanti",
    "ogni quante",
    "con che frequenza",
    "con quale frequenza",
    "quante volte",
    "ogni",
    "ogni giorno",
    "ogni settimana",
    "ogni mese",
    "ogni anno",
    "giornalmente",
    "settimanalmente",
    "mensilmente",
    "annualmente",
    "periodicamente",
    "regolarmente",
    
    # — PASSATO —
    "passato",
    "nel passato",
    "in passato",
    "tempo fa",
    "fa",
    "anni fa",
    "mesi fa",
    "giorni fa",
    "prima",
    "in precedenza",
    "precedentemente",
    "antecedente",
    "anteriore",
    "scorso",
    "scorsa",
    "scorsi",
    "scorse",
    "l'anno scorso",
    "il mese scorso",
    "la settimana scorsa",
    "ieri",
    "l'altro ieri",
    
    # — PRESENTE —
    "ora",
    "adesso",
    "attualmente",
    "al momento",
    "in questo momento",
    "oggigiorno",
    "oggi",
    "quest'anno",
    "questo mese",
    "questa settimana",
    "corrente",
    "anno corrente",
    "mese corrente",
    "in corso",
    "anno in corso",
    "mese in corso",
    
    # — FUTURO —
    "futuro",
    "nel futuro",
    "in futuro",
    "prossimo",
    "prossima",
    "prossimi",
    "prossime",
    "l'anno prossimo",
    "il mese prossimo",
    "la settimana prossima",
    "venturo",
    "ventura",
    "imminente",
    "a breve",
    "a breve termine",
    "domani",
    "dopodomani",
    "tra",
    "tra un giorno",
    "tra una settimana",
    "tra un mese",
    "tra un anno",
    "entro",
    "entro domani",
    "entro una settimana",
    
    # — CRONOLOGIA E SEQUENZA —
    "cronologia",
    "cronologia di",
    "cronologia del",
    "cronologia della",
    "ordine cronologico",
    "in ordine cronologico",
    "sequenza",
    "sequenza di",
    "sequenza temporale",
    "timeline",
    "linea temporale",
    "successione",
    "successione di",
    "prima di",
    "dopo",
    "dopo di",
    "in seguito",
    "in seguito a",
    "successivamente",
    "successivamente a",
    "poi",
    "quindi",
    "antecedente a",
    "precedente a",
    "anteriore a",
    "posteriore a",
    "seguente",
    
    # — CONTEMPORANEITÀ —
    "contemporaneo",
    "contemporanea",
    "contemporanei",
    "contemporanee",
    "nello stesso tempo",
    "allo stesso tempo",
    "contemporaneamente",
    "simultaneo",
    "simultanea",
    "simultanei",
    "simultanee",
    "simultaneamente",
    "insieme",
    "assieme",
    "nel mentre",
    "mentre",
    
    # — RICORRENZE —
    "ricorrenza",
    "ricorrenze",
    "anniversario",
    "anniversari",
    "celebrazione",
    "celebrazioni",
    "festività",
    "festa",
    "feste",
    "evento",
    "eventi",
    "quando ricorre",
    "quando si celebra",
    
    # — PUNTUALITÀ E RITARDI —
    "in tempo",
    "in orario",
    "puntuale",
    "puntualmente",
    "puntualità",
    "ritardo",
    "ritardi",
    "in ritardo",
    "con ritardo",
    "anticipo",
    "in anticipo",
    "con anticipo",
    "prima del tempo",
    "prima del previsto",
    
    # — SCADENZE E TERMINI —
    "scadenza",
    "scadenze",
    "termine",
    "termini",
    "termine ultimo",
    "entro il",
    "entro la",
    "entro i",
    "limite",
    "limite di tempo",
    "limite temporale",
    "deadline",
    "dead line",
    
    # — STAGIONI —
    "stagione",
    "stagioni",
    "primavera",
    "estate",
    "autunno",
    "inverno",
    "in primavera",
    "in estate",
    "in autunno",
    "in inverno",
]

# Set minimale greedy per fallback rapido
TEMPORAL_QUERY_MINIMAL_PATTERNS = [
    # Interrogativi base
    "quando",
    "da quando",
    "fino a quando",
    
    # Date/tempo
    "data",
    "giorno",
    "anno",
    "mese",
    "ora",
    "orario",
    
    # Periodi
    "periodo",
    "epoca",
    "secolo",
    
    # Inizio/fine
    "inizio",
    "fine",
    "scadenza",
    "termine",
    
    # Durata
    "durata",
    "quanto dura",
    "per quanto tempo",
    
    # Frequenza
    "ogni quanto",
    "frequenza",
    
    # Passato/presente/futuro
    "fa",
    "scorso",
    "prossimo",
    "attualmente",
    "futuro",
    
    # Cronologia
    "cronologia",
    "prima di",
    "dopo",
]
