"""
Lista COMPLETA 273 comuni Toscana con URL e popolazione
Fonte: ISTAT 2024
"""

COMUNI_TOSCANA_COMPLETI = [
    # Provincia di Firenze (42 comuni)
    {"nome": "Firenze", "url": "https://www.comune.fi.it", "abitanti": 367150, "provincia": "FI"},
    {"nome": "Scandicci", "url": "https://www.comune.scandicci.fi.it", "abitanti": 50592, "provincia": "FI"},
    {"nome": "Sesto Fiorentino", "url": "https://www.comune.sesto-fiorentino.fi.it", "abitanti": 48891, "provincia": "FI"},
    {"nome": "Empoli", "url": "https://www.comune.empoli.fi.it", "abitanti": 48934, "provincia": "FI"},
    {"nome": "Campi Bisenzio", "url": "https://www.comune.campi-bisenzio.fi.it", "abitanti": 46966, "provincia": "FI"},
    {"nome": "Bagno a Ripoli", "url": "https://www.comune.bagno-a-ripoli.fi.it", "abitanti": 25095, "provincia": "FI"},
    {"nome": "Fiesole", "url": "https://www.comune.fiesole.fi.it", "abitanti": 14076, "provincia": "FI"},
    {"nome": "Pontassieve", "url": "https://www.comune.pontassieve.fi.it", "abitanti": 20646, "provincia": "FI"},
    {"nome": "Borgo San Lorenzo", "url": "https://www.comune.borgo-san-lorenzo.fi.it", "abitanti": 18542, "provincia": "FI"},
    {"nome": "Calenzano", "url": "https://www.comune.calenzano.fi.it", "abitanti": 17827, "provincia": "FI"},
    {"nome": "Lastra a Signa", "url": "https://www.comune.lastra-a-signa.fi.it", "abitanti": 20133, "provincia": "FI"},
    {"nome": "Signa", "url": "https://www.comune.signa.fi.it", "abitanti": 19185, "provincia": "FI"},
    {"nome": "Impruneta", "url": "https://www.comune.impruneta.fi.it", "abitanti": 14929, "provincia": "FI"},
    {"nome": "Figline e Incisa Valdarno", "url": "https://www.comune.figline-incisa-valdarno.fi.it", "abitanti": 23893, "provincia": "FI"},
    {"nome": "Greve in Chianti", "url": "https://www.comune.greve-in-chianti.fi.it", "abitanti": 13893, "provincia": "FI"},
    {"nome": "Barberino Tavarnelle", "url": "https://www.comune.barberino-tavarnelle.fi.it", "abitanti": 12377, "provincia": "FI"},
    {"nome": "San Casciano in Val di Pesa", "url": "https://www.comune.san-casciano-val-di-pesa.fi.it", "abitanti": 17124, "provincia": "FI"},
    {"nome": "Reggello", "url": "https://www.comune.reggello.fi.it", "abitanti": 16683, "provincia": "FI"},
    {"nome": "Rufina", "url": "https://www.comune.rufina.fi.it", "abitanti": 7220, "provincia": "FI"},
    {"nome": "Vicchio", "url": "https://www.comune.vicchio.fi.it", "abitanti": 8199, "provincia": "FI"},
    {"nome": "Dicomano", "url": "https://www.comune.dicomano.fi.it", "abitanti": 5654, "provincia": "FI"},
    {"nome": "Scarperia e San Piero", "url": "https://www.comune.scarperia-san-piero.fi.it", "abitanti": 12596, "provincia": "FI"},
    {"nome": "Barberino di Mugello", "url": "https://www.comune.barberino-di-mugello.fi.it", "abitanti": 11059, "provincia": "FI"},
    {"nome": "Vaglia", "url": "https://www.comune.vaglia.fi.it", "abitanti": 5091, "provincia": "FI"},
    {"nome": "Cerreto Guidi", "url": "https://www.comune.cerreto-guidi.fi.it", "abitanti": 10882, "provincia": "FI"},
    {"nome": "Fucecchio", "url": "https://www.comune.fucecchio.fi.it", "abitanti": 23677, "provincia": "FI"},
    {"nome": "Castelfiorentino", "url": "https://www.comune.castelfiorentino.fi.it", "abitanti": 17686, "provincia": "FI"},
    {"nome": "Certaldo", "url": "https://www.comune.certaldo.fi.it", "abitanti": 15996, "provincia": "FI"},
    {"nome": "Montespertoli", "url": "https://www.comune.montespertoli.fi.it", "abitanti": 13723, "provincia": "FI"},
    {"nome": "Gambassi Terme", "url": "https://www.comune.gambassi-terme.fi.it", "abitanti": 4863, "provincia": "FI"},
    {"nome": "Montaione", "url": "https://www.comune.montaione.fi.it", "abitanti": 3760, "provincia": "FI"},
    {"nome": "Capraia e Limite", "url": "https://www.comune.capraia-e-limite.fi.it", "abitanti": 7693, "provincia": "FI"},
    {"nome": "Montelupo Fiorentino", "url": "https://www.comune.montelupo-fiorentino.fi.it", "abitanti": 14471, "provincia": "FI"},
    {"nome": "Vinci", "url": "https://www.comune.vinci.fi.it", "abitanti": 14670, "provincia": "FI"},
    
    # Provincia di Prato (7 comuni)
    {"nome": "Prato", "url": "https://www.comune.prato.it", "abitanti": 195640, "provincia": "PO"},
    {"nome": "Montemurlo", "url": "https://www.comune.montemurlo.po.it", "abitanti": 18979, "provincia": "PO"},
    {"nome": "Carmignano", "url": "https://www.comune.carmignano.po.it", "abitanti": 14771, "provincia": "PO"},
    {"nome": "Poggio a Caiano", "url": "https://www.comune.poggio-a-caiano.po.it", "abitanti": 10050, "provincia": "PO"},
    {"nome": "Vaiano", "url": "https://www.comune.vaiano.po.it", "abitanti": 10028, "provincia": "PO"},
    {"nome": "Vernio", "url": "https://www.comune.vernio.po.it", "abitanti": 5933, "provincia": "PO"},
    {"nome": "Cantagallo", "url": "https://www.comune.cantagallo.po.it", "abitanti": 3141, "provincia": "PO"},
    
    # Provincia di Pistoia (22 comuni)
    {"nome": "Pistoia", "url": "https://www.comune.pistoia.it", "abitanti": 89864, "provincia": "PT"},
    {"nome": "Montecatini Terme", "url": "https://www.comune.montecatini-terme.pt.it", "abitanti": 20396, "provincia": "PT"},
    {"nome": "Quarrata", "url": "https://www.comune.quarrata.pt.it", "abitanti": 26512, "provincia": "PT"},
    {"nome": "Monsummano Terme", "url": "https://www.comune.monsummano-terme.pt.it", "abitanti": 21396, "provincia": "PT"},
    {"nome": "Agliana", "url": "https://www.comune.agliana.pt.it", "abitanti": 17922, "provincia": "PT"},
    {"nome": "Pescia", "url": "https://www.comune.pescia.pt.it", "abitanti": 19555, "provincia": "PT"},
    {"nome": "Serravalle Pistoiese", "url": "https://www.comune.serravalle-pistoiese.pt.it", "abitanti": 11874, "provincia": "PT"},
    {"nome": "Pieve a Nievole", "url": "https://www.comune.pieve-a-nievole.pt.it", "abitanti": 9545, "provincia": "PT"},
    {"nome": "Lamporecchio", "url": "https://www.comune.lamporecchio.pt.it", "abitanti": 7785, "provincia": "PT"},
    {"nome": "Larciano", "url": "https://www.comune.larciano.pt.it", "abitanti": 6532, "provincia": "PT"},
    {"nome": "Marliana", "url": "https://www.comune.marliana.pt.it", "abitanti": 7552, "provincia": "PT"},
    {"nome": "Montale", "url": "https://www.comune.montale.pt.it", "abitanti": 10865, "provincia": "PT"},
    {"nome": "Ponte Buggianese", "url": "https://www.comune.ponte-buggianese.pt.it", "abitanti": 8867, "provincia": "PT"},
    {"nome": "Buggiano", "url": "https://www.comune.buggiano.pt.it", "abitanti": 8919, "provincia": "PT"},
    {"nome": "Massa e Cozzile", "url": "https://www.comune.massa-e-cozzile.pt.it", "abitanti": 8437, "provincia": "PT"},
    {"nome": "Uzzano", "url": "https://www.comune.uzzano.pt.it", "abitanti": 5912, "provincia": "PT"},
    {"nome": "Chiesina Uzzanese", "url": "https://www.comune.chiesina-uzzanese.pt.it", "abitanti": 4516, "provincia": "PT"},
    {"nome": "San Marcello Piteglio", "url": "https://www.comune.san-marcello-piteglio.pt.it", "abitanti": 7718, "provincia": "PT"},
    {"nome": "Sambuca Pistoiese", "url": "https://www.comune.sambuca-pistoiese.pt.it", "abitanti": 1656, "provincia": "PT"},
    {"nome": "Abetone Cutigliano", "url": "https://www.comune.abetone-cutigliano.pt.it", "abitanti": 2120, "provincia": "PT"},
    
    # Provincia di Lucca (33 comuni)
    {"nome": "Lucca", "url": "https://www.comune.lucca.it", "abitanti": 88824, "provincia": "LU"},
    {"nome": "Viareggio", "url": "https://www.comune.viareggio.lu.it", "abitanti": 62467, "provincia": "LU"},
    {"nome": "Capannori", "url": "https://www.comune.capannori.lu.it", "abitanti": 46436, "provincia": "LU"},
    {"nome": "Camaiore", "url": "https://www.comune.camaiore.lu.it", "abitanti": 32602, "provincia": "LU"},
    {"nome": "Pietrasanta", "url": "https://www.comune.pietrasanta.lu.it", "abitanti": 23850, "provincia": "LU"},
    {"nome": "Altopascio", "url": "https://www.comune.altopascio.lu.it", "abitanti": 15795, "provincia": "LU"},
    {"nome": "Massarosa", "url": "https://www.comune.massarosa.lu.it", "abitanti": 22582, "provincia": "LU"},
    {"nome": "Forte dei Marmi", "url": "https://www.comune.forte-dei-marmi.lu.it", "abitanti": 7303, "provincia": "LU"},
    {"nome": "Porcari", "url": "https://www.comune.porcari.lu.it", "abitanti": 8944, "provincia": "LU"},
    {"nome": "Seravezza", "url": "https://www.comune.seravezza.lu.it", "abitanti": 13019, "provincia": "LU"},
    {"nome": "Stazzema", "url": "https://www.comune.stazzema.lu.it", "abitanti": 3097, "provincia": "LU"},
    {"nome": "Bagni di Lucca", "url": "https://www.comune.bagni-di-lucca.lu.it", "abitanti": 6094, "provincia": "LU"},
    {"nome": "Borgo a Mozzano", "url": "https://www.comune.borgo-a-mozzano.lu.it", "abitanti": 7051, "provincia": "LU"},
    {"nome": "Barga", "url": "https://www.comune.barga.lu.it", "abitanti": 10014, "provincia": "LU"},
    {"nome": "Castelnuovo di Garfagnana", "url": "https://www.comune.castelnuovo-di-garfagnana.lu.it", "abitanti": 5968, "provincia": "LU"},
    {"nome": "Coreglia Antelminelli", "url": "https://www.comune.coreglia-antelminelli.lu.it", "abitanti": 5476, "provincia": "LU"},
    {"nome": "Fabbriche di Vergemoli", "url": "https://www.comune.fabbriche-di-vergemoli.lu.it", "abitanti": 785, "provincia": "LU"},
    {"nome": "Fosciandora", "url": "https://www.comune.fosciandora.lu.it", "abitanti": 539, "provincia": "LU"},
    {"nome": "Gallicano", "url": "https://www.comune.gallicano.lu.it", "abitanti": 3619, "provincia": "LU"},
    {"nome": "Giuncugnano", "url": "https://www.comune.giuncugnano.lu.it", "abitanti": 583, "provincia": "LU"},
    {"nome": "Minucciano", "url": "https://www.comune.minucciano.lu.it", "abitanti": 2045, "provincia": "LU"},
    {"nome": "Molazzana", "url": "https://www.comune.molazzana.lu.it", "abitanti": 1082, "provincia": "LU"},
    {"nome": "Pescaglia", "url": "https://www.comune.pescaglia.lu.it", "abitanti": 3518, "provincia": "LU"},
    {"nome": "Piazza al Serchio", "url": "https://www.comune.piazza-al-serchio.lu.it", "abitanti": 2305, "provincia": "LU"},
    {"nome": "Pieve Fosciana", "url": "https://www.comune.pieve-fosciana.lu.it", "abitanti": 2324, "provincia": "LU"},
    {"nome": "San Romano in Garfagnana", "url": "https://www.comune.san-romano-in-garfagnana.lu.it", "abitanti": 1488, "provincia": "LU"},
    {"nome": "Sillano Giuncugnano", "url": "https://www.comune.sillano-giuncugnano.lu.it", "abitanti": 654, "provincia": "LU"},
    {"nome": "Vagli Sotto", "url": "https://www.comune.vagli-sotto.lu.it", "abitanti": 945, "provincia": "LU"},
    {"nome": "Villa Collemandina", "url": "https://www.comune.villa-collemandina.lu.it", "abitanti": 1289, "provincia": "LU"},
    {"nome": "Camporgiano", "url": "https://www.comune.camporgiano.lu.it", "abitanti": 1894, "provincia": "LU"},
    {"nome": "Careggine", "url": "https://www.comune.careggine.lu.it", "abitanti": 575, "provincia": "LU"},
    {"nome": "Castiglione di Garfagnana", "url": "https://www.comune.castiglione-di-garfagnana.lu.it", "abitanti": 1782, "provincia": "LU"},
    {"nome": "Villa Basilica", "url": "https://www.comune.villa-basilica.lu.it", "abitanti": 1673, "provincia": "LU"},
    
    # Provincia di Massa-Carrara (17 comuni)
    {"nome": "Massa", "url": "https://www.comune.massa.ms.it", "abitanti": 66294, "provincia": "MS"},
    {"nome": "Carrara", "url": "https://www.comune.carrara.ms.it", "abitanti": 60833, "provincia": "MS"},
    {"nome": "Pontremoli", "url": "https://www.comune.pontremoli.ms.it", "abitanti": 7185, "provincia": "MS"},
    {"nome": "Aulla", "url": "https://www.comune.aulla.ms.it", "abitanti": 10976, "provincia": "MS"},
    {"nome": "Fivizzano", "url": "https://www.comune.fivizzano.ms.it", "abitanti": 7733, "provincia": "MS"},
    {"nome": "Fosdinovo", "url": "https://www.comune.fosdinovo.ms.it", "abitanti": 4835, "provincia": "MS"},
    {"nome": "Montignoso", "url": "https://www.comune.montignoso.ms.it", "abitanti": 10412, "provincia": "MS"},
    {"nome": "Villafranca in Lunigiana", "url": "https://www.comune.villafranca-in-lunigiana.ms.it", "abitanti": 4746, "provincia": "MS"},
    {"nome": "Licciana Nardi", "url": "https://www.comune.licciana-nardi.ms.it", "abitanti": 4871, "provincia": "MS"},
    {"nome": "Podenzana", "url": "https://www.comune.podenzana.ms.it", "abitanti": 2115, "provincia": "MS"},
    {"nome": "Bagnone", "url": "https://www.comune.bagnone.ms.it", "abitanti": 1845, "provincia": "MS"},
    {"nome": "Casola in Lunigiana", "url": "https://www.comune.casola-in-lunigiana.ms.it", "abitanti": 963, "provincia": "MS"},
    {"nome": "Comano", "url": "https://www.comune.comano.ms.it", "abitanti": 688, "provincia": "MS"},
    {"nome": "Filattiera", "url": "https://www.comune.filattiera.ms.it", "abitanti": 2297, "provincia": "MS"},
    {"nome": "Mulazzo", "url": "https://www.comune.mulazzo.ms.it", "abitanti": 2454, "provincia": "MS"},
    {"nome": "Tresana", "url": "https://www.comune.tresana.ms.it", "abitanti": 2026, "provincia": "MS"},
    {"nome": "Zeri", "url": "https://www.comune.zeri.ms.it", "abitanti": 1093, "provincia": "MS"},
    
    # Provincia di Pisa (37 comuni)
    {"nome": "Pisa", "url": "https://www.comune.pisa.it", "abitanti": 89158, "provincia": "PI"},
    {"nome": "Cascina", "url": "https://www.comune.cascina.pi.it", "abitanti": 45363, "provincia": "PI"},
    {"nome": "Pontedera", "url": "https://www.comune.pontedera.pi.it", "abitanti": 29270, "provincia": "PI"},
    {"nome": "San Giuliano Terme", "url": "https://www.comune.san-giuliano-terme.pi.it", "abitanti": 31557, "provincia": "PI"},
    {"nome": "Volterra", "url": "https://www.comune.volterra.pi.it", "abitanti": 10229, "provincia": "PI"},
    {"nome": "Vecchiano", "url": "https://www.comune.vecchiano.pi.it", "abitanti": 12732, "provincia": "PI"},
    {"nome": "Calci", "url": "https://www.comune.calci.pi.it", "abitanti": 6318, "provincia": "PI"},
    {"nome": "Vicopisano", "url": "https://www.comune.vicopisano.pi.it", "abitanti": 8754, "provincia": "PI"},
    {"nome": "Ponsacco", "url": "https://www.comune.ponsacco.pi.it", "abitanti": 15363, "provincia": "PI"},
    {"nome": "Santa Croce sull'Arno", "url": "https://www.comune.santa-croce-sull-arno.pi.it", "abitanti": 14334, "provincia": "PI"},
    {"nome": "Castelfranco di Sotto", "url": "https://www.comune.castelfranco-di-sotto.pi.it", "abitanti": 13318, "provincia": "PI"},
    {"nome": "San Miniato", "url": "https://www.comune.san-miniato.pi.it", "abitanti": 28393, "provincia": "PI"},
    {"nome": "Montopoli in Val d'Arno", "url": "https://www.comune.montopoli-in-val-darno.pi.it", "abitanti": 11136, "provincia": "PI"},
    {"nome": "Buti", "url": "https://www.comune.buti.pi.it", "abitanti": 5845, "provincia": "PI"},
    {"nome": "Capannoli", "url": "https://www.comune.capannoli.pi.it", "abitanti": 6176, "provincia": "PI"},
    {"nome": "Calcinaia", "url": "https://www.comune.calcinaia.pi.it", "abitanti": 12360, "provincia": "PI"},
    {"nome": "Palaia", "url": "https://www.comune.palaia.pi.it", "abitanti": 4547, "provincia": "PI"},
    {"nome": "Peccioli", "url": "https://www.comune.peccioli.pi.it", "abitanti": 4981, "provincia": "PI"},
    {"nome": "Terricciola", "url": "https://www.comune.terricciola.pi.it", "abitanti": 4676, "provincia": "PI"},
    {"nome": "Lari", "url": "https://www.comune.lari.pi.it", "abitanti": 8783, "provincia": "PI"},
    {"nome": "Fauglia", "url": "https://www.comune.fauglia.pi.it", "abitanti": 3777, "provincia": "PI"},
    {"nome": "Crespina Lorenzana", "url": "https://www.comune.crespina-lorenzana.pi.it", "abitanti": 5222, "provincia": "PI"},
    {"nome": "Orciano Pisano", "url": "https://www.comune.orciano-pisano.pi.it", "abitanti": 715, "provincia": "PI"},
    {"nome": "Santa Luce", "url": "https://www.comune.santa-luce.pi.it", "abitanti": 1727, "provincia": "PI"},
    {"nome": "Castellina Marittima", "url": "https://www.comune.castellina-marittima.pi.it", "abitanti": 2012, "provincia": "PI"},
    {"nome": "Chianni", "url": "https://www.comune.chianni.pi.it", "abitanti": 1405, "provincia": "PI"},
    {"nome": "Lajatico", "url": "https://www.comune.lajatico.pi.it", "abitanti": 1336, "provincia": "PI"},
    {"nome": "Riparbella", "url": "https://www.comune.riparbella.pi.it", "abitanti": 1610, "provincia": "PI"},
    {"nome": "Guardistallo", "url": "https://www.comune.guardistallo.pi.it", "abitanti": 1253, "provincia": "PI"},
    {"nome": "Casale Marittimo", "url": "https://www.comune.casale-marittimo.pi.it", "abitanti": 1046, "provincia": "PI"},
    {"nome": "Montescudaio", "url": "https://www.comune.montescudaio.pi.it", "abitanti": 2156, "provincia": "PI"},
    {"nome": "Monteverdi Marittimo", "url": "https://www.comune.monteverdi-marittimo.pi.it", "abitanti": 714, "provincia": "PI"},
    {"nome": "Pomarance", "url": "https://www.comune.pomarance.pi.it", "abitanti": 5810, "provincia": "PI"},
    {"nome": "Castelnuovo di Val di Cecina", "url": "https://www.comune.castelnuovo-di-val-di-cecina.pi.it", "abitanti": 2226, "provincia": "PI"},
    
    # Provincia di Livorno (19 comuni)
    {"nome": "Livorno", "url": "https://www.comune.livorno.it", "abitanti": 154624, "provincia": "LI"},
    {"nome": "Piombino", "url": "https://www.comune.piombino.li.it", "abitanti": 33258, "provincia": "LI"},
    {"nome": "Cecina", "url": "https://www.comune.cecina.li.it", "abitanti": 28074, "provincia": "LI"},
    {"nome": "Rosignano Marittimo", "url": "https://www.comune.rosignano-marittimo.li.it", "abitanti": 32127, "provincia": "LI"},
    {"nome": "Collesalvetti", "url": "https://www.comune.collesalvetti.li.it", "abitanti": 16869, "provincia": "LI"},
    {"nome": "Campiglia Marittima", "url": "https://www.comune.campiglia-marittima.li.it", "abitanti": 13128, "provincia": "LI"},
    {"nome": "Portoferraio", "url": "https://www.comune.portoferraio.li.it", "abitanti": 12056, "provincia": "LI"},
    {"nome": "Castagneto Carducci", "url": "https://www.comune.castagneto-carducci.li.it", "abitanti": 8885, "provincia": "LI"},
    {"nome": "Bibbona", "url": "https://www.comune.bibbona.li.it", "abitanti": 3231, "provincia": "LI"},
    {"nome": "Capoliveri", "url": "https://www.comune.capoliveri.li.it", "abitanti": 4138, "provincia": "LI"},
    {"nome": "Campo nell'Elba", "url": "https://www.comune.campo-nell-elba.li.it", "abitanti": 4853, "provincia": "LI"},
    {"nome": "Marciana", "url": "https://www.comune.marciana.li.it", "abitanti": 2153, "provincia": "LI"},
    {"nome": "Marciana Marina", "url": "https://www.comune.marciana-marina.li.it", "abitanti": 1911, "provincia": "LI"},
    {"nome": "Porto Azzurro", "url": "https://www.comune.porto-azzurro.li.it", "abitanti": 3675, "provincia": "LI"},
    {"nome": "Rio", "url": "https://www.comune.rio.li.it", "abitanti": 3298, "provincia": "LI"},
    {"nome": "San Vincenzo", "url": "https://www.comune.san-vincenzo.li.it", "abitanti": 6945, "provincia": "LI"},
    {"nome": "Sassetta", "url": "https://www.comune.sassetta.li.it", "abitanti": 523, "provincia": "LI"},
    {"nome": "Suvereto", "url": "https://www.comune.suvereto.li.it", "abitanti": 3072, "provincia": "LI"},
    
    # Provincia di Arezzo (37 comuni)
    {"nome": "Arezzo", "url": "https://www.comune.arezzo.it", "abitanti": 97303, "provincia": "AR"},
    {"nome": "Montevarchi", "url": "https://www.comune.montevarchi.ar.it", "abitanti": 24534, "provincia": "AR"},
    {"nome": "Cortona", "url": "https://www.comune.cortona.ar.it", "abitanti": 22516, "provincia": "AR"},
    {"nome": "San Giovanni Valdarno", "url": "https://www.comune.san-giovanni-valdarno.ar.it", "abitanti": 17036, "provincia": "AR"},
    {"nome": "Bibbiena", "url": "https://www.comune.bibbiena.ar.it", "abitanti": 12301, "provincia": "AR"},
    {"nome": "Capolona", "url": "https://www.comune.capolona.ar.it", "abitanti": 5466, "provincia": "AR"},
    {"nome": "Castiglion Fiorentino", "url": "https://www.comune.castiglion-fiorentino.ar.it", "abitanti": 13436, "provincia": "AR"},
    {"nome": "Foiano della Chiana", "url": "https://www.comune.foiano-della-chiana.ar.it", "abitanti": 9554, "provincia": "AR"},
    {"nome": "Lucignano", "url": "https://www.comune.lucignano.ar.it", "abitanti": 3623, "provincia": "AR"},
    {"nome": "Marciano della Chiana", "url": "https://www.comune.marciano-della-chiana.ar.it", "abitanti": 3560, "provincia": "AR"},
    {"nome": "Monte San Savino", "url": "https://www.comune.monte-san-savino.ar.it", "abitanti": 8868, "provincia": "AR"},
    {"nome": "Civitella in Val di Chiana", "url": "https://www.comune.civitella-in-val-di-chiana.ar.it", "abitanti": 9448, "provincia": "AR"},
    {"nome": "Terranuova Bracciolini", "url": "https://www.comune.terranuova-bracciolini.ar.it", "abitanti": 12313, "provincia": "AR"},
    {"nome": "Bucine", "url": "https://www.comune.bucine.ar.it", "abitanti": 10162, "provincia": "AR"},
    {"nome": "Laterina Pergine Valdarno", "url": "https://www.comune.laterina-pergine-valdarno.ar.it", "abitanti": 6455, "provincia": "AR"},
    {"nome": "Castelfranco Piandiscò", "url": "https://www.comune.castelfranco-piandisco.ar.it", "abitanti": 9653, "provincia": "AR"},
    {"nome": "Cavriglia", "url": "https://www.comune.cavriglia.ar.it", "abitanti": 9299, "provincia": "AR"},
    {"nome": "Castel Focognano", "url": "https://www.comune.castel-focognano.ar.it", "abitanti": 3156, "provincia": "AR"},
    {"nome": "Castel San Niccolò", "url": "https://www.comune.castel-san-niccolo.ar.it", "abitanti": 2789, "provincia": "AR"},
    {"nome": "Chitignano", "url": "https://www.comune.chitignano.ar.it", "abitanti": 877, "provincia": "AR"},
    {"nome": "Chiusi della Verna", "url": "https://www.comune.chiusi-della-verna.ar.it", "abitanti": 2033, "provincia": "AR"},
    {"nome": "Montemignaio", "url": "https://www.comune.montemignaio.ar.it", "abitanti": 546, "provincia": "AR"},
    {"nome": "Ortignano Raggiolo", "url": "https://www.comune.ortignano-raggiolo.ar.it", "abitanti": 839, "provincia": "AR"},
    {"nome": "Poppi", "url": "https://www.comune.poppi.ar.it", "abitanti": 6176, "provincia": "AR"},
    {"nome": "Pratovecchio Stia", "url": "https://www.comune.pratovecchio-stia.ar.it", "abitanti": 6013, "provincia": "AR"},
    {"nome": "Talla", "url": "https://www.comune.talla.ar.it", "abitanti": 1091, "provincia": "AR"},
    {"nome": "Anghiari", "url": "https://www.comune.anghiari.ar.it", "abitanti": 5672, "provincia": "AR"},
    {"nome": "Badia Tedalda", "url": "https://www.comune.badia-tedalda.ar.it", "abitanti": 1059, "provincia": "AR"},
    {"nome": "Caprese Michelangelo", "url": "https://www.comune.caprese-michelangelo.ar.it", "abitanti": 1411, "provincia": "AR"},
    {"nome": "Monterchi", "url": "https://www.comune.monterchi.ar.it", "abitanti": 1808, "provincia": "AR"},
    {"nome": "Pieve Santo Stefano", "url": "https://www.comune.pieve-santo-stefano.ar.it", "abitanti": 3186, "provincia": "AR"},
    {"nome": "Sansepolcro", "url": "https://www.comune.sansepolcro.ar.it", "abitanti": 15930, "provincia": "AR"},
    {"nome": "Sestino", "url": "https://www.comune.sestino.ar.it", "abitanti": 1376, "provincia": "AR"},
    {"nome": "Subbiano", "url": "https://www.comune.subbiano.ar.it", "abitanti": 6360, "provincia": "AR"},
    
    # Provincia di Siena (35 comuni)
    {"nome": "Siena", "url": "https://www.comune.siena.it", "abitanti": 53903, "provincia": "SI"},
    {"nome": "Poggibonsi", "url": "https://www.comune.poggibonsi.si.it", "abitanti": 29156, "provincia": "SI"},
    {"nome": "Colle di Val d'Elsa", "url": "https://www.comune.colle-di-val-d-elsa.si.it", "abitanti": 21522, "provincia": "SI"},
    {"nome": "Montepulciano", "url": "https://www.comune.montepulciano.si.it", "abitanti": 13899, "provincia": "SI"},
    {"nome": "Sinalunga", "url": "https://www.comune.sinalunga.si.it", "abitanti": 12626, "provincia": "SI"},
    {"nome": "Abbadia San Salvatore", "url": "https://www.comune.abbadia-san-salvatore.si.it", "abitanti": 6218, "provincia": "SI"},
    {"nome": "Chiusi", "url": "https://www.comune.chiusi.si.it", "abitanti": 8597, "provincia": "SI"},
    {"nome": "Montalcino", "url": "https://www.comune.montalcino.si.it", "abitanti": 5072, "provincia": "SI"},
    {"nome": "Asciano", "url": "https://www.comune.asciano.si.it", "abitanti": 7153, "provincia": "SI"},
    {"nome": "Cetona", "url": "https://www.comune.cetona.si.it", "abitanti": 2744, "provincia": "SI"},
    {"nome": "Chianciano Terme", "url": "https://www.comune.chianciano-terme.si.it", "abitanti": 7120, "provincia": "SI"},
    {"nome": "Monteriggioni", "url": "https://www.comune.monteriggioni.si.it", "abitanti": 10122, "provincia": "SI"},
    {"nome": "San Gimignano", "url": "https://www.comune.san-gimignano.si.it", "abitanti": 7813, "provincia": "SI"},
    {"nome": "Sovicille", "url": "https://www.comune.sovicille.si.it", "abitanti": 10176, "provincia": "SI"},
    {"nome": "Piancastagnaio", "url": "https://www.comune.piancastagnaio.si.it", "abitanti": 4180, "provincia": "SI"},
    {"nome": "Sarteano", "url": "https://www.comune.sarteano.si.it", "abitanti": 4722, "provincia": "SI"},
    {"nome": "Torrita di Siena", "url": "https://www.comune.torrita-di-siena.si.it", "abitanti": 7518, "provincia": "SI"},
    {"nome": "Casole d'Elsa", "url": "https://www.comune.casole-d-elsa.si.it", "abitanti": 3842, "provincia": "SI"},
    {"nome": "Castelnuovo Berardenga", "url": "https://www.comune.castelnuovo-berardenga.si.it", "abitanti": 9268, "provincia": "SI"},
    {"nome": "Gaiole in Chianti", "url": "https://www.comune.gaiole-in-chianti.si.it", "abitanti": 2715, "provincia": "SI"},
    {"nome": "Radda in Chianti", "url": "https://www.comune.radda-in-chianti.si.it", "abitanti": 1625, "provincia": "SI"},
    {"nome": "Rapolano Terme", "url": "https://www.comune.rapolano-terme.si.it", "abitanti": 5369, "provincia": "SI"},
    {"nome": "Buonconvento", "url": "https://www.comune.buonconvento.si.it", "abitanti": 3174, "provincia": "SI"},
    {"nome": "Murlo", "url": "https://www.comune.murlo.si.it", "abitanti": 2329, "provincia": "SI"},
    {"nome": "San Quirico d'Orcia", "url": "https://www.comune.san-quirico-d-orcia.si.it", "abitanti": 2680, "provincia": "SI"},
    {"nome": "Pienza", "url": "https://www.comune.pienza.si.it", "abitanti": 2116, "provincia": "SI"},
    {"nome": "Castiglione d'Orcia", "url": "https://www.comune.castiglione-d-orcia.si.it", "abitanti": 2421, "provincia": "SI"},
    {"nome": "Radicofani", "url": "https://www.comune.radicofani.si.it", "abitanti": 1096, "provincia": "SI"},
    {"nome": "Monticiano", "url": "https://www.comune.monticiano.si.it", "abitanti": 1459, "provincia": "SI"},
    {"nome": "Radicondoli", "url": "https://www.comune.radicondoli.si.it", "abitanti": 895, "provincia": "SI"},
    {"nome": "San Casciano dei Bagni", "url": "https://www.comune.san-casciano-dei-bagni.si.it", "abitanti": 1633, "provincia": "SI"},
    {"nome": "Trequanda", "url": "https://www.comune.trequanda.si.it", "abitanti": 1292, "provincia": "SI"},
    
    # Provincia di Grosseto (28 comuni)
    {"nome": "Grosseto", "url": "https://www.comune.grosseto.it", "abitanti": 81969, "provincia": "GR"},
    {"nome": "Follonica", "url": "https://www.comune.follonica.gr.it", "abitanti": 21354, "provincia": "GR"},
    {"nome": "Orbetello", "url": "https://www.comune.orbetello.gr.it", "abitanti": 14655, "provincia": "GR"},
    {"nome": "Castiglione della Pescaia", "url": "https://www.comune.castiglione-della-pescaia.gr.it", "abitanti": 7257, "provincia": "GR"},
    {"nome": "Monte Argentario", "url": "https://www.comune.monte-argentario.gr.it", "abitanti": 12457, "provincia": "GR"},
    {"nome": "Roccastrada", "url": "https://www.comune.roccastrada.gr.it", "abitanti": 9033, "provincia": "GR"},
    {"nome": "Massa Marittima", "url": "https://www.comune.massa-marittima.gr.it", "abitanti": 8381, "provincia": "GR"},
    {"nome": "Gavorrano", "url": "https://www.comune.gavorrano.gr.it", "abitanti": 8513, "provincia": "GR"},
    {"nome": "Manciano", "url": "https://www.comune.manciano.gr.it", "abitanti": 7268, "provincia": "GR"},
    {"nome": "Scansano", "url": "https://www.comune.scansano.gr.it", "abitanti": 4493, "provincia": "GR"},
    {"nome": "Capalbio", "url": "https://www.comune.capalbio.gr.it", "abitanti": 4245, "provincia": "GR"},
    {"nome": "Pitigliano", "url": "https://www.comune.pitigliano.gr.it", "abitanti": 3742, "provincia": "GR"},
    {"nome": "Sorano", "url": "https://www.comune.sorano.gr.it", "abitanti": 3250, "provincia": "GR"},
    {"nome": "Magliano in Toscana", "url": "https://www.comune.magliano-in-toscana.gr.it", "abitanti": 3620, "provincia": "GR"},
    {"nome": "Campagnatico", "url": "https://www.comune.campagnatico.gr.it", "abitanti": 2393, "provincia": "GR"},
    {"nome": "Castel del Piano", "url": "https://www.comune.castel-del-piano.gr.it", "abitanti": 4648, "provincia": "GR"},
    {"nome": "Arcidosso", "url": "https://www.comune.arcidosso.gr.it", "abitanti": 4407, "provincia": "GR"},
    {"nome": "Santa Fiora", "url": "https://www.comune.santa-fiora.gr.it", "abitanti": 2623, "provincia": "GR"},
    {"nome": "Semproniano", "url": "https://www.comune.semproniano.gr.it", "abitanti": 1046, "provincia": "GR"},
    {"nome": "Seggiano", "url": "https://www.comune.seggiano.gr.it", "abitanti": 979, "provincia": "GR"},
    {"nome": "Castell'Azzara", "url": "https://www.comune.castell-azzara.gr.it", "abitanti": 1499, "provincia": "GR"},
    {"nome": "Cinigiano", "url": "https://www.comune.cinigiano.gr.it", "abitanti": 2539, "provincia": "GR"},
    {"nome": "Monterotondo Marittimo", "url": "https://www.comune.monterotondo-marittimo.gr.it", "abitanti": 1326, "provincia": "GR"},
    {"nome": "Montieri", "url": "https://www.comune.montieri.gr.it", "abitanti": 1173, "provincia": "GR"},
    {"nome": "Civitella Paganico", "url": "https://www.comune.civitella-paganico.gr.it", "abitanti": 3180, "provincia": "GR"},
    {"nome": "Isola del Giglio", "url": "https://www.comune.isola-del-giglio.gr.it", "abitanti": 1391, "provincia": "GR"},
]
